emberjs/ember-inspector

- dist_chrome/manifest.json
- dist_chrome/options-dialog.html
Migrate to new options dialog, as [recommended](https://developer.chrome.com/extensions/optionsV2#migration).
> Options dialog

- app/components/action-checkbox.js
- app/controllers/promise-tree.js
- app/routes/promise-tree.js
- app/templates/promise-tree-toolbar.handlebars
- ember_debug/main.js
- ember_debug/promise-debug.js
- ember_debug/services/session.js
- tests/ember_debug/promise_debug_test.js
> Store instrumentWithStack in session storage for reloads

- ember_debug/adapters/basic.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/port.js
- ember_debug/promise-debug.js
- ember_debug/route-debug.js
> computed.readOnly is only for Ember >= 1.4

- ember_debug/vendor/loader.js
Fixes https://github.com/emberjs/ember-inspector/issues/304
> Fix for apps where define or requireModule are not both defined

- ember_debug/route-debug.js
> Fix Ember canary resolver bug

- ember_debug/vendor/startup-wrapper.js
Use new hook added in https://github.com/emberjs/ember.js/pull/10377
> Use the new Ember load hook if available

- ember_debug/object-inspector.js
See https://github.com/emberjs/ember.js/pull/10672
Fixes https://github.com/emberjs/ember-inspector/issues/326
> Descriptor is no longer exposed on the Ember global.

- Brocfile.js
- package.json
Part of https://github.com/emberjs/ember-inspector/issues/360
> Add Babel support to ember-debug

- ember_debug/data-debug.js
- ember_debug/object-inspector.js
Support for https://github.com/emberjs/ember.js/pull/11346 and https://github.com/emberjs/data/pull/3203
> Add support for passing model names to the data adapter

- package.json
Fixes https://github.com/emberjs/ember-inspector/issues/407
> Fix broccoli-babel-transpiler version to 5.1.0

- app/controllers/view-tree.js
- ember_debug/view-debug.js
Fixes https://github.com/emberjs/ember-inspector/issues/408
> Fix sending view model to console

- ember_debug/deprecation-debug.js
- ember_debug/vendor/source-map.js
New source-map.js has perf improvements (My deprecations source map calculation decreased from 9s to 5s  in my app).
Related to https://github.com/emberjs/ember-inspector/issues/422
> Update source-map.js and fix deprecation error

- ember_debug/object-inspector.js
Fixes https://github.com/emberjs/ember-inspector/issues/449
> [BUGFIX] Fix value of this after ES6 refactor

- app/controllers/model-types.js
- app/routes/model-types.js
- app/templates/model-types-toolbar.hbs
Improvement for https://github.com/emberjs/ember-inspector/issues/455
> Add 'Hide empty models' filter

- ember_debug/data-debug.js
see:
http://emberjs.com/deprecations/v2.x/#toc_ember-application-registry-ember-applicationinstance-registry
> fix registry.resolve deprecation

- CHANGELOG.md
- app/app.js
- bower.json
- ember_debug/.eslintrc
- ember_debug/adapters/websocket.js
- ember_debug/view-debug.js
- package.json
- skeleton_chrome/manifest.json
- skeleton_firefox/package.json
> Version 1.9.5

- Brocfile.js
- skeleton_chrome/devtools.js
- skeleton_firefox/lib/tomster-devtool-panel.js
> Add [DEV] to the tab name for the inspector development version

- app/helpers/escape-url.js
- app/routes/model-type.js
- app/templates/model-types.hbs
Fixes https://github.com/emberjs/ember-inspector/issues/548
> Encode model name containing / in URL

- app/controllers/route-tree.js
Hi,
This adds the queryParam as requested here
https://github.com/emberjs/ember-inspector/issues/567
I haven't written a test, but have tried it locally and it appears to work.
> Current route only persists now after changing tabs if checked

- package.json
Resolves https://github.com/emberjs/ember-inspector/issues/577
> Bump `babel-broccoli-transpiler` to 5.5.0

- app/components/x-list-content.js
- app/components/x-list.js
- tests/acceptance/data-test.js
Fixes https://github.com/emberjs/ember-inspector/issues/586
> Rebuild columns when schema changes

- CHANGELOG.md
Fixes https://github.com/emberjs/ember-inspector/issues/591
> Add changelog for 2.0.0, 2.0.1, 2.0.2

- app/schemas/render-tree.js
- app/templates/components/render-item.hbs
- app/templates/render-tree.hbs
> Splits render time into separate column

- ember_debug/libs/glimmer-tree.js
... for components that don't have a parent controller
Resolves #598
> glimmer-tree: Add controller null checks

- ember_debug/route-debug.js
- tests/ember_debug/route-debug-test.js
Fixes https://github.com/emberjs/ember-inspector/issues/611
> Only list subroutes if they are defined

- ember_debug/route-debug.js
> Fix lookupFactory deprecation

- ember_debug/object-inspector.js
- ember_debug/route-debug.js
> Fix router.router deprecation warnings

- ember_debug/adapters/basic.js
- ember_debug/adapters/bookmarklet.js
- ember_debug/adapters/websocket.js
- ember_debug/general-debug.js
There is more work to do, but i'd rather keep merging advances as I make them.
> Start removing jQuery

- config/environment.js
Part 2 (of 2) to fix the Ember Inspector on master.
cc @cibernox
> Remove / from the root URL since we're using relative URLs

- ember_debug/adapters/basic.js
- ember_debug/adapters/websocket.js
- ember_debug/utils/on-ready.js
- ember_debug/vendor/startup-wrapper.js
Part 1 (of 2) to fix the Ember Inspector on master.
Original code is by @bloodyowl
This PR fixes the failing tests in https://github.com/emberjs/ember-inspector/pull/686
> Document ready

- ember_debug/adapters/basic.js
- ember_debug/adapters/websocket.js
- ember_debug/utils/on-ready.js
- ember_debug/vendor/startup-wrapper.js
Extracted the one from startup-wrapper and made a module out of it
> Add onReady

- shared/in-page-script.js
- yarn.lock
@teddyzeenny  Copy-pasted the utility as this file is isolated.
> Remove dependency on jQuery for boot

- ember_debug/view-debug.js
> Fix element highlighting after removing jQuery

- app/components/x-list-content.js
- tests/acceptance/view-tree-test.js
Continues the work in https://github.com/emberjs/ember-inspector/pull/698 by simulating mouseleave as well and fixes the failing test.
cc @cibernox
> Fix event delegation change

- app/styles/split.scss
made quick fix for background issue in split panel. 
related to this issue https://github.com/emberjs/ember-inspector/issues/699
> fixed the background of split panel

- ember_debug/object-inspector.js
- ember_debug/utils/version.js
- ember_debug/vendor/startup-wrapper.js
Fixes https://github.com/emberjs/ember-inspector/issues/706
> Only call Mixin#toString on Ember > 2.11

- package.json
Not releasing, just bumping the minor version so that master is always one minor version ahead of stable.
> Bump version to 2.2.0

- CHANGELOG.md
- package.json
This will be a FF-only release.
> Bump patch version to 2.3.1

- ember_debug/object-inspector.js
> Allow for empty mixins

- package.json
- tests/acceptance/container-test.js
- tests/acceptance/data-test.js
- tests/acceptance/deprecation-test.js
- tests/acceptance/info-test.js
- tests/acceptance/object-inspector-test.js
- tests/acceptance/promise-test.js
- tests/acceptance/render-tree-test.js
- tests/acceptance/route-tree-test.js
- tests/acceptance/view-tree-test.js
- tests/ember_debug/container-debug-test.js
- tests/ember_debug/deprecation-debug-test.js
- tests/ember_debug/ember-debug-test.js
- tests/ember_debug/object-inspector-test.js
- tests/ember_debug/profile-node-test.js
- tests/ember_debug/promise-assembler-test.js
- tests/ember_debug/promise-debug-test.js
- tests/ember_debug/render-debug-test.js
- tests/ember_debug/route-debug-test.js
- tests/ember_debug/view-debug-test.js
- tests/unit/build-style-test.js
- tests/unit/check-current-route-test.js
- tests/unit/ms-to-time-test.js
- tests/unit/resizable-columns-test.js
- yarn.lock
Ran ember-qunit-codemod to update test formats
> ember-qunit-codemod

- app/controllers/application.js
- app/routes/app-detected.js
- app/templates/application.hbs
- ember_debug/general-debug.js
Documented: 
- `app/routes/app-detected.js` 
- Part of `ember_debug/general-debug.js`
> Add Documentation + Minor Cleanup

- tests/ember_debug/view-debug-test.js
Since this was updated in beta as well, things started failing, this should fix it.
> Fix text field assertion

- app/components/search-field.js
- app/templates/components/search-field.hbs
- tests/acceptance/container-test.js
- tests/acceptance/data-test.js
- tests/acceptance/deprecation-test.js
- tests/acceptance/promise-test.js
- tests/acceptance/render-tree-test.js
- tests/acceptance/view-tree-test.js
Changed clear button from DOM removal to 0 opacity because this causes problems in testing. When clicking on a button, it gets focus. But if you remove a focused element from the DOM, the entire window loses focus.
> search-field  Component Bug Fix and Acceptance Tests

- .bowerrc
- .travis.yml
- bower.json
- package.json
- yarn.lock
I don't think we needed the bower deps anymore, but definitely correct me if I am wrong on that @teddyzeenny.
> Remove bower deps

- app/components/drag-handle.js
- app/libs/resizable-columns.js
- app/templates/components/x-list.hbs
Fixes #803 
Fixes #813
Closes #805
> Fix toggling and resizing table columns

- .npmignore
Thanks @jacobq for pointing it out 👍
> Avoid publishing secrets file to npm

- ember_debug/object-inspector.js
> Add targetObject to skipProperties

- ember_debug/deprecation-debug.js
- tests/ember_debug/deprecation-debug-test.js
> Handle deprecations with registerDeprecationHandler

- ember_debug/object-inspector.js
> Bind to object to fix debugInfo

- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
> Fix issue with Proxy services

- app/controllers/route-tree.js
- app/templates/route-tree-toolbar.hbs
- app/utils/is-route-substate.js
- tests/acceptance/route-tree-test.js
- tests/unit/is-route-substate-test.js
Resolves https://github.com/emberjs/ember-inspector/issues/502
> Route Tree: Hide Substates Checkbox

- tests/acceptance/data-test.js
I couldn't find a test for the hiding empty models toggle, so I added one.
> Add test for hideEmptyModelTypes

- app/controllers/component-tree.js
Avoid scrolling to visible elements and match the behavior of the Elements panel.
> Components view scrolling

- .travis.yml
- ember_debug/view-debug.js
> Use [class='ember-view'] to avoid liquid-fire etc

- app/routes/model-types.js
- app/templates/model-types-toolbar.hbs
- tests/acceptance/data-test.js
> Add a Refresh button to the Data Tab

- tests/ember_debug/promise-debug-test.js
Just skipping the test that intermittently fails
> Skip promise debug test that fails

- app/routes/launch.js
- tests/acceptance/view-tree-test.js
> Default to Components Route

- lib/ui/addon/components/error-page.js
> Fix Error Page Console Error

- app/controllers/container-type.js
- app/controllers/deprecations.js
- app/controllers/render-tree.js
- app/controllers/view-tree.js
- ember_debug/promise-debug.js
- tests/ember_debug/object-inspector-test.js
Fixes https://github.com/emberjs/ember-inspector/issues/944
> Remove usage of .property() syntax for setting CP keys

- app/components/mixin-property.js
- app/utils/parse-text.js
- tests/unit/utils/parse-text-test.js
> Ensure we do not add quotes twice to strings when edited

- ember_debug/route-debug.js
> Use router.currentPath instead of applicationController

- app/styles/component_tree.scss
> Fix hover colors of selected component

- ember_debug/libs/glimmer-tree.js
Glimmer components do not have `.get`
> fix glimmer tree

- package.json
- yarn.lock
Fixes #1064 
I think this will fix things.
> Remove ember-cli-sri

- ember_debug/object-inspector.js
Fixes #1068
Older ember version did not have glimmer.value...
Any other way to do this?
> Fix glimmer.value

- .github/workflows/build.yml
- ember-cli-build.js
- skeletons/firefox/lib/tomster-devtool-panel.js
- skeletons/web-extension/devtools.js
This commit uploads the artifacts from pull requests, allow PRs to be easily tested in Chrome/Firefox/etc before merging into master.
General instructions for testing PRs:
1. Click on the "Checks" tabs in the pull request, wait for the "Build and Publish" > "Build extensions" CI job to finish.
2. Under the "Artifacts" dropdown of the CI job, download either the "chrome" or "firefox" build.
3. Extract the zip file. It should result in a "chrome" or "firefox" folder.
4. For Chrome:
4.1. Navigate to `chrome://extensions/`.
4.2. Make sure "Developer mode" (top-right corner) is enabled.
4.3. Disable the Ember Inspector extension (if you have it).
4.4. Click the "Load unpacked" button.
4.5. Select the "chrome" folder from step 3.
5. For Firefox:
5.1. Navigate to `about:addons` and choose …
> Upload PR artifacts

- ember_debug/adapters/web-extension.js
> Fix prototype extensions detection

- CHANGELOG.md
(cherry picked from commit 1263a942b4e8ef327360ec5dd0b8703a4b8ea34e)
> v3.13.1 CHANGELOG

- tests/ember_debug/view-debug-test.js
See https://github.com/emberjs/ember.js/issues/18673
> Fix canary test failure

- ember_debug/object-inspector.js
Updates the imports for various autotracking APIs, since they changed during the VM upgrade.
> [BUGFIX] Updates "import" paths for autotracking APIs

- CHANGELOG.md
(cherry picked from commit bfb90b31c10a9d9d8857cd340da8913195cb4416)
> CHANGELOG for v3.13.2

- ember_debug/object-inspector.js
args is a proxy and does not have a constructor
> fix component args inspect

- ember_debug/object-inspector.js
Updates the autotracking APIs, which have been renamed upstream.
N/A
> [BUGFIX] Updates autotracking APIs

- ember_debug/object-inspector.js
> attrs does not have constructor

- package.json
Updates to 4.0.0 so we can publish a new major version
> Update to major version 4.0.0

- CHANGELOG.md
- package.json
> Add 4.0.0 changelog, bump minor version

- app/app.js
- app/router.js
- config/ember-cli-update.json
- config/targets.js
- package.json
- yarn.lock
> ember-cli 3.20

- RELEASE.md
- package.json
- yarn.lock
> Add rwjblue release-it config

- CHANGELOG.md
- package.json
Push tag using `release-it`
See [original PR](https://github.com/emberjs/ember-inspector/pull/1520) for context
> Release 4.3.5

- ember_debug/container-debug.js
- ember_debug/data-debug.js
- ember_debug/debug-port.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/object-inspector.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/route-debug.js
- ember_debug/view-debug.js
remove port mixin
All tests passed, smoke tested.
> remove port mixin

- ember_debug/utils/rsvp.js
Discussed this in Discord with @chancancode. There was a bug starting the inspector in FF. This fixes it, tho I'm not sure this is the right thing to do to fix it.
> fix startup bug in Firefox (fixes #1770)

- app/controllers/application.js
> Try to fix owner errors

- app/routes/whats-new.js
- tests/acceptance/whats-new-test.js
> bug: Find the latest entry created by lerna-changelog

- tests/ember_debug/container-debug-test.js
> Skip flaky container:types test

- tests/ember_debug/container-debug-test.js
> Disable more flaky tests

- ember_debug/libs/source-map.js
> Fix setting _lastPromise computed deprecation

- .eslintrc.js
- app/components/list-cell.hbs
- app/components/list-cell.js
- app/components/list.js
- app/components/scroll-container.js
- lib/ui/addon/components/open-links-in-new-window.hbs
- lib/ui/addon/components/open-links-in-new-window.js
> Enable ember/require-tagless-components

- .github/workflows/build.yml
I accidentally swapped the two extension IDs
> Fix chrome publishing again

- app/components/component-tree-toolbar.hbs
- app/components/container-type-toolbar.hbs
- app/components/deprecations-toolbar.hbs
- app/components/promise-tree-toolbar.hbs
- app/components/records-toolbar.hbs
- app/components/render-tree-toolbar.hbs
- app/components/route-tree-toolbar.hbs
- app/controllers/render-tree.js
- app/utils/escape-reg-exp.js
- lib/ui/addon/components/toolbar-search-field.js
> Convert ToolbarSearchField to glimmer

- app/controllers/application.js
- app/controllers/model-types.js
- app/controllers/records.js
- app/controllers/render-tree.js
> Convert controllers to native classes

- ember_debug/libs/view-inspection.js
increased z-index for highlight and tooltip to prevent overlapping in some applications
> enhancement(view-inspection): increased z-index for highlight and tooltip

- app/services/adapters/web-extension.js
fix placeholder issue in production build having replaced single quotes with double quotes
and a few other things....
> fix ember inspector not loading

- package.json
- yarn.lock
> Remove unused dep `del`

- app/components/object-inspector/accordion.js
- app/components/object-inspector/sort-properties.js
- app/components/promise-item.js
- app/components/route-cell-name.js
> Convert some components to glimmer

- package.json
- yarn.lock
> Add back del

- .github/workflows/build.yml
- config/ember-try.js
- package.json
> Target Ember 3.16+ for main branch

- .github/workflows/build.yml
- README.md
- app/routes/whats-new.js
- tests/acceptance/whats-new-test.js
> Update all master refs to main

- ember_debug/libs/render-tree.js
- tests/ember_debug/view-debug-test.js
> correctly serialize args for internal components like Input

- app/services/adapters/web-extension.js
- app/services/port.js
- tests/acceptance/app-picker-test.js
inspector does not refresh the view when switching apps. it requires to manually switch routers to get the right data.
this makes it work when switching apps.
also it did not detect the iframe if it was already loaded before inspector was opened
> fix app switching

- ember_debug/object-inspector.js
instead of overwriting willDestroy
fixes #1225
another possibility would be to use registerDestructor. but I think this is more backwards compatible
> iterate check over retained objects if they are destroyed

- .github/workflows/build.yml
Bump github actions to latest version.
Main change - actions move to node 16
> Bump Github actions

- .github/workflows/build.yml
missing path for download artifact
https://geeksrepos.com/actions/download-artifact#compatibility-between-v1-and-v2v3
> fix publishing 

- app/controllers/component-tree.js
renderNode needs to be tracked as it can be updated
> [bug] tree view sometimes not updating children

- ember_debug/render-debug.js
this happens sometimes when there are quick successive renders. with  _backburner.on('end' it seems to work reliable.
> [bug] component tree sometimes does not update

- tests/ember_debug/ember-data-test.js
> add minimal data debug test

- app/templates/component-tree.hbs
- app/templates/deprecations.hbs
- app/templates/promise-tree.hbs
- package.json
- tests/acceptance/component-tree-test.js
- tests/test-adapter.js
- tests/test-helper.js
- yarn.lock
> update vertical-collection & ember-table

- ember_debug/main.js
- ember_debug/vendor/startup-wrapper.js
- jsconfig.json
- tests/integration/injection-test.js
during the tests I also found that _applicationInstances is now a Set, therefore _applicationInstances[0] will not work
> add context menu test

- app/routes/whats-new.js
replace icon placeholders from lerna-changelog with actual icons
> show icons in whats-new page

- skeletons/web-extension/background.js
- skeletons/web-extension/content-script.js
- skeletons/web-extension/manifest.json
- tests/integration/injection-test.js
> Convert to manifest v3

- app/routes/application.js
when digging into props and error happend there where not shown
> fix missing errors when digging into props

- README.md
- RELEASE.md
- package.json
A follow-up to https://github.com/emberjs/ember-inspector/pull/2411.
Also updates `lock-version` script, a single line in RELEASE.md, and Firefox extension instructions.
n/a
> Update README.md with pnpm usage

- ember_debug/container-debug.js
> [container debug] fix missing message handling

- .github/workflows/build.yml
> Remove custom id setting since it is in manifest

- ember_debug/object-inspector.js
property can be a number
fixes #2530
> fix cannot access array values

- .github/workflows/build.yml
versions where mismatching, some master other v3, update all to v4
> fix ci artifact upload & download

- ember_debug/utils/base-object.js
- ember_debug/view-debug.js
> fix render tree triggering when already destroyed

- ember_debug/libs/render-tree.js
ember beta & canary now have support for in-element & modifiers in debug render tree
> fix beta & canary tests

- ember_debug/deprecation-debug.js
> do not use prototype extension

- .github/workflows/publish.yml
> Use Personal Access Token

- app/components/list-content.ts
> Remove unused evented from ListContent

- app/controllers/application.js
- app/controllers/promise-tree.js
- app/controllers/promise-tree.ts
- app/models/promise.ts
- app/routes/application.js
- app/services/port.ts
- tests/ember_debug/object-inspector-test.js
- tests/ember_debug/promise-assembler-test.js
> Remove gets and access props directly

- package.json
> fix watch test script
