emberjs/ember-inspector

- config/environment.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/route-debug.js
- tests/ember_debug/route_debug_test.js
The route tab class names now take into account: globals and modules and pod-modules.
Fixes #196
> Fix naming to account for module based names

- ember_debug/promise-debug.js
> Only destroy the promise assembler if it exists

- ember_debug/libs/source-map.js
Fixes #312.
This PR fixes an issue where `ember_debug/libs/source-map.js` assumes Ember's prototype extensions are enabled. If they aren't, then the inspector will crash upon loading.
> Fix errors when EXTEND_PROTOTYPES=false

- app/models/promise.js
- app/routes/deprecations.js
- package.json
> Use "ember-new-computed" to polyfill new CP syntax 

- app/routes/container-type.js
- ember_debug/container-debug.js
- tests/ember_debug/container_debug_test.js
- tests/integration/container_test.js
If the container type does not exist we redirect back to the list of
container types.
Fixes https://github.com/emberjs/ember-inspector/issues/314
> Handle case where container type no longer exists after reload

- app/controllers/application.js
- app/controllers/mixin-detail.js
- app/controllers/mixin-details.js
- app/routes/application.js
- app/styles/mixin.scss
- app/templates/mixin-details.hbs
- ember_debug/object-inspector.js
- tests/ember_debug/object_inspector_test.js
- tests/integration/object_inspector_test.js
Fixes https://github.com/emberjs/ember-inspector/issues/222
Opening an object in the inspector means we eagerly calculate all of that object's CPs. Sometimes CPs that don't expect to be calculated yet may throw an error (for example CPs that depend on another property that hasn't been set yet). 
Previously, the object inspector just wouldn't open, and the thrown errors were displayed in the app's console.
After this PR these errors are caught by the inspector and displayed above the object's properties.
> Handle and display errors caused by CP calculation in the object inspector

- ember_debug/addons/ember-new-computed/index.js
- ember_debug/addons/ember-new-computed/utils/can-use-new-syntax.js
- ember_debug/models/promise.js
I've been getting deprecation warnings in my app coming from `ember_debug/models/promise.js`.
Now it uses the `ember-computed-new` addon, that is already being used in other areas.
> Use ember-computed-new in ember-debug to avoid warnings

- app/components/view-item.js
- app/controllers/view-tree.js
- app/templates/view-item.hbs
- ember_debug/deprecation-debug.js
- ember_debug/object-inspector.js
- ember_debug/view-debug.js
- eslint.json
- tests/ember_debug/deprecation_debug_test.js
- tests/ember_debug/ember_debug_test.js
- tests/ember_debug/promise_debug_test.js
- tests/ember_debug/route_debug_test.js
- tests/ember_debug/view_debug_test.js
- tests/helpers/start-app.js
- tests/integration/container_test.js
- tests/integration/data_test.js
- tests/integration/info_test.js
- tests/integration/promise_test.js
- tests/integration/render_tree_test.js
- tests/integration/route_tree_test.js
- tests/integration/view_tree_test.js
Fixes #351 
Fixes https://github.com/emberjs/ember.js/issues/11027 
Fixes #356
There was a shift in concept from a view tree to a render node tree.
Previously, the template tree was made of a hierarchy of view instances.
After the Glimmer rewrite, view instances are optional and secondary, and the main template representation is a render node tree.
This required a re-write of all of view-debug.js. Old code was left untouched, so the current version supports both pre-glimmer and post-glimmer. We detect glimmer by checking for the absence of `_childViews` on the top level view.
All code that touches private api (anything that has to do with render nodes) needs to be moved to Ember core and tested.
> [Glimmer] The view tree now supports glimmer

- Brocfile.js
- ember_debug/adapters/basic.js
- ember_debug/models/profile-manager.js
- ember_debug/port.js
- ember_debug/render-debug.js
- ember_debug/vendor/startup-wrapper.js
- tests/ember_debug/ember_debug_test.js
Ember Inspector caused errors are now caught in production and logged as warnings instead of being thrown.
> Catch errors triggered by the inspector.

- ember_debug/deprecation-debug.js
- ember_debug/libs/source-map.js
- tests/ember_debug/deprecation_debug_test.js
Previously, if deprecations were triggered on page load (before the app boots), the page could freeze for up to 1 minute.
- Unlike the browser, we don't need to get the source map synchronously. Make everything async.
- Only compute source maps and parse deprecations when requested instead of when triggered.
cc @wagenet @ebryn
> Speed up the deprecations tab

- ember_debug/deprecation-debug.js
- ember_debug/libs/source-map.js
Passing `ember-inspector` label to promises will tell the Promise Tab to ignore them.
> Ignore promises created by deprecation debug

- ember_debug/promise-debug.js
Fixes deprecation warning with Ember 1.12.0. Fixes #361. Note this is untested (dry-coded on Github).
> Switch computed property with get/set to polyfill

- README.md
- package.json
First I want to thank everyone working on this for an amazing tool.
While setting up the project on my machine I noticed that `run` was missing from a couple of commands in the README.md.
Figured I would create a PR instead of just opening an issue, hope that is ok. 
Cheers,
Björn
> `run` is missing from a couple of build commands

- ember_debug/vendor/startup-wrapper.js
- ember_debug/view-debug.js
- Renamed `Ember.Debug` to `Ember.EmberInspectorDebugger`
- Removed any calls to `Ember.View.addMutationListener`
- Use `-view-registry:main` instead of `Ember.View.views`
Fixes https://github.com/emberjs/ember-inspector/issues/392
Fixes https://github.com/emberjs/ember-inspector/issues/315
> Fixes for Ember >= 1.13

- app/routes/route-tree.js
- ember_debug/route-debug.js
- tests/ember_debug/route_debug_test.js
Having more than one top route (application, application_loading, application_error) broke the routes pane.
Fixes https://github.com/emberjs/ember-inspector/issues/396
> Fix routes pane for Ember >= 1.13

- ember_debug/adapters/basic.js
- ember_debug/adapters/bookmarklet.js
- ember_debug/adapters/chrome.js
- ember_debug/adapters/firefox.js
- ember_debug/adapters/websocket.js
- ember_debug/addons/ember-new-computed/index.js
- ember_debug/addons/ember-new-computed/utils/can-use-new-syntax.js
- ember_debug/container-debug.js
- ember_debug/data-debug.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/libs/promise-assembler.js
- ember_debug/libs/source-map.js
- ember_debug/main.js
- ember_debug/mixins/port-mixin.js
- ember_debug/models/profile-manager.js
- ember_debug/models/profile-node.js
- ember_debug/models/promise.js
- ember_debug/object-inspector.js
- ember_debug/port.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/route-debug.js
- ember_debug/services/session.js
- ember_debug/view-debug.js
OK, I believe this is ready, But, there are a few problems that I faced:
- I couldn't refactor the contents of `/vendor`, when I tried, I got an error "Can't use block-scoped let, const out of restricted mode."
- Because arrow functions should always be anonymous, I couldn't/figure out how to refactor [this one](https://github.com/emberjs/ember-inspector/blob/master/ember_debug/view-debug.js#L192) to use `this` instead of `self`
similar problem with [this one](https://github.com/emberjs/ember-inspector/blob/master/ember_debug/deprecation-debug.js#L177)
As always, Any suggestions, comments, notes, things to be changed or feedback is always appreciated
> - Refactor ember-debug to use ES6.

- ember_debug/view-debug.js
This addresses the issue raised in #416
> Guard against renderNode not being rendered yet

- ember_debug/view-debug.js
This should address #365, where components inside an {{#each}} are not
inspected.
Feedback on this is greatly appreciated!
> Components Inside an Each Added to View Tree

- ember_debug/adapters/basic.js
Using an arrow function here prevent this from being undefined and thus allowing the code to actually clear the interval
> Use an arrow function to preserve this value

- ember_debug/adapters/chrome.js
- ember_debug/deprecation-debug.js
If Ember prototype extensions are disabled Chrome refuses to clone Ember arrays. We need to turn them into native arrays before sending them.
Fixes https://github.com/emberjs/ember-inspector/issues/366
> Clone Ember arrays before sending them in Chrome

- skeleton_chrome/content-script.js
If a content script is injected into an iframe, it shouldn't reset the Tomster because the parent window may be an Ember app.
Fixes https://github.com/emberjs/ember-inspector/issues/418
> Don't clear tomster in iframe content scripts.

- ember_debug/view-debug.js
Fixes https://github.com/emberjs/ember-inspector/issues/432
> Check existence of renderNode.lastResult

- app/styles/sidebar_toggle.scss
- app/styles/toolbar.scss
- app/templates/main.hbs
- app/templates/mixin-stack.hbs
Fixes https://github.com/emberjs/ember-inspector/issues/434
> Make sure the object inspector toggle button is always visible

- ember_debug/view-debug.js
This change is necessary but not sufficient to use ember-inspector with current canary.
(Still exploring what else is broken -- we apparently have a problem with Streams being sealed.)
> Update getState and getLocals for compatibility with canary

- ember_debug/view-debug.js
No `Ember.View` in Ember >= 2.0.
cc @wagenet
> Don't assume Ember.View exists

- skeleton_firefox/lib/devtools-utils.js
In Firefox 44, we are [moving DevTools files][1] to a new location. This impacts some add-ons that import those files at their old paths.
For Ember, there's only two imports to clean up.
I've updated the add-on to use the new path when available (Firefox 44 and later) and fallback to the old one if not.
I tested this add-on build in Firefox 43 and 44.
At the moment, the old path also works in 44, but we'll soon start logging deprecation warnings for the old paths, so now you'll already be updated to avoid such warnings.
[1]: https://bugzil.la/912121
> Update Firefox skeleton for path change in Firefox 44 and later

- ember_debug/vendor/startup-wrapper.js
Ember 2.1+ issue a deprecation when using 2 arguments with initializers.
This tweak ensures that our initializer works without deprecation for  all Ember versions.
> Prevent deprecation for initializer arguments.

- skeleton_chrome/content-script.js
If `document.documentElement` does not have a `dataset` property we will never mark the content script as loaded (and it cannot be an Ember app) this happens in some scenarios with Chrome 45+ and SVG elements.
Fixes #463
Closes #473
> Prevent errors when document.documentElement.dataset is not present.

- shared/in-page-script.js
- skeleton_chrome/background-script.js
- skeleton_chrome/content-script.js
- skeleton_chrome/devtools.js
- skeleton_chrome/options.js
- tests/ember_debug/object_inspector_test.js
Work for #378 
This is a first pass at documentation for the chrome extension files for EmberInspector:
- content-script.js
- background-script.js
- in-page-script.js
- devtools.js
- options.js
I wanted to understand the setup and communication flow before getting into the
internals of either EmberDebug or EmberInspector.  The basic pattern is outlined
here, https://developer.chrome.com/extensions/devtools#more, but I wanted to see
exactly how it is all happening.
**There is one logic change**: I removed the setTimeout that called sendIframe in content-script.js.  This seemed unnecessary since EmberInspector calls _injectDebugger() during setup.  Everything
still works locally, but I'm not sure if that is necessary for backward compatibility.
Some Questions:
- Is camel case naming for the …
> Adding documentation for extension-level files

- ember_debug/vendor/startup-wrapper.js
If you call `reopen` in an object's method on the object itself `_super` will be reset and can no longer be used.
This stores `_super` in a variable to we can call it later.
Fixes https://github.com/emberjs/ember-inspector/issues/461
Fixes https://github.com/emberjs/ember-inspector/issues/478
Fixes https://github.com/emberjs/ember.js/issues/12439
> Save _super before reopening

- app/components/drag-handle.js
- app/components/record-item.js
- app/components/resizable-column.js
- app/components/route-item.js
- app/components/view-item.js
- app/controllers/promise-item.js
- app/controllers/render-item.js
- app/styles/list_view.scss
- app/views/instance-list.js
- app/views/list-item.js
- app/views/list.js
- app/views/promise-list.js
- app/views/record-list.js
- app/views/render-list.js
- app/views/route-list.js
- app/views/view-list.js
- bower.json
- ember_debug/object-inspector.js
- package.json
- tests/integration/object_inspector_test.js
Upgraded ember list view to v 0.0.6
Added SafeString to style bindings
Part of #360
> Upgraded to ember 1.12.0

- skeleton_firefox/lib/devtools-utils.js
In #470, I updated some internal Firefox DevTools paths for 44 and later.
On the Firefox DevTools team, we made [one more change][1] that also landed in 44, so here's another update to cover that. No other changes like this are anticipated in the near future.
[1]: https://bugzil.la/1203159
> Tweak Firefox skeleton again for 44 and later

- ember_debug/view-debug.js
`controller` local has been removed from templates.
Fixes https://github.com/emberjs/ember-inspector/issues/494
> Use scope.getSelf when available to get the controller

- ember_debug/vendor/startup-wrapper.js
This fixes a bug where the inspector wouldn't launch if it's opened after the page has loaded but not "completed".
> Launch inspector if document ready state is "interactive"

- ember_debug/adapters/websocket.js
The conversion to ES6 of this file a long time back broke it apparently as the scope of `this` was lost in this function
> Fix websocket adapter ES6 conversion

- ember_debug/view-debug.js
> filter out null/undefined nodes

- Gruntfile.js
- package.json
- skeleton_firefox/lib/tomster-locationbar-button.js
- skeleton_firefox/package.json
This PR fixes #518 by applying small changes in the grunt-based xpi building process to use jpm (through grunt-jpm) instead of cfx (through grunt-mozilla-addon-sdk).
A couple on minor tweaks of the Firefox package.json and javascript sources have been necessary to fix minor incompatibilities between cfx and jpm.
> Port gruntfile to grunt-jpm to build an valid xpi for Firefox 44+

- skeleton_chrome/content-script.js
There's an issue in all current Chrome versions, where the built-in PDF-Viewer only displays a blank page, if the Ember Inspector extension is active.
This fix works around the issue, by skipping the injection if the document's content type is reported as PDF which should never be true for normal HTML pages.
Fixes #532.
For a test case see issue #532.
> Skip in page script injection in Chrome PDF Viewer

- app/controllers/container-type.js
- app/mixins/fake-table.js
- app/styles/base.scss
- app/styles/fake_table.scss
- app/templates/container-type.hbs
- app/templates/instance-item.hbs
- app/templates/list.hbs
- app/templates/promise-item.hbs
- app/templates/record-item.hbs
- app/templates/route-item.hbs
- app/templates/view-item.hbs
- app/views/list-item.js
- app/views/list.js
- app/views/view-list.js
- package.json
List-view has blocked us at Ember 1.12. We need to remove it if we want
to move on. We can look into alternatives as soon as we upgrade Ember.
> Remove usage of list-view so we can upgrade Ember.

- skeletons/bookmarklet/load_inspector.js
I've tried the [bookmarklet](https://github.com/emberjs/ember-inspector#bookmarklet-all-browsers) approach in Safari and caught unexpected ES6 syntax in the http://ember-extension.s3.amazonaws.com/dist_bookmarklet/load_inspector.js
> Remove arrow function syntax from bookmarklet/load_inspector.js

- ember_debug/adapters/chrome.js
Resolves feature deprecation warning in Chrome Canary V53; legacy window.postMessage overload https://www.chromestatus.com/features/5719033043222528
> Fix deprecated window.postMessage overload

- app/components/main-content.js
- app/components/x-list-content.js
- app/components/x-list.js
- app/controllers/application.js
- app/services/layout.js
- app/templates/-main.hbs
- app/templates/components/x-list.hbs
- app/templates/container-type.hbs
- app/templates/deprecations.hbs
- app/templates/info.hbs
- app/templates/promise-tree.hbs
- app/templates/records.hbs
- app/templates/render-tree.hbs
- app/templates/route-tree.hbs
- app/templates/view-tree.hbs
This allows us to also trigger events whenever the content height changes. Events are needed to re-render the x-list content due to smoke and mirrors not being aware that content height has changed and requiring a rerender.
To reproduce the bug that this commit fixes:
- Open the inspector on an Ember.js app.
- Switch to the Console (or any other devtools tab).
- Reload the page (Inspector has now loaded but with height 0 since it's not visible).
- Visit the inspector.
Before this commit the view tree would only have one visible row due to smoke and mirrors not being aware that content height has changed.
> Use the layout service to pass content height to lists

- app/adapters/chrome.js
- app/components/view-item.js
- app/controllers/view-tree.js
- app/routes/view-tree.js
- app/templates/components/view-item.hbs
- app/templates/view-tree-toolbar.hbs
- ember_debug/adapters/chrome.js
- ember_debug/libs/glimmer-tree.js
- ember_debug/utils/name-functions.js
- ember_debug/vendor/startup-wrapper.js
- ember_debug/view-debug.js
- tests/acceptance/view-tree-test.js
- tests/ember_debug/ember-debug-test.js
- tests/ember_debug/view-debug-test.js
> Glimmer 2 support

- ember-cli-build.js
Source map file will not exist when Ember Debug is injected.
> Disable source map for ember_debug.js

- ember_debug/libs/glimmer-tree.js
This uses APIs that are too private. I think it may be good to have something like `ViewUtils.getRootElement`.
> [GLIMMER] New way to get the root element

- app/components/x-list.js
- app/libs/resizable-columns.js
- app/services/storage/local.js
- app/services/storage/memory.js
- tests/unit/resizable-columns-test.js
Fixes https://github.com/emberjs/ember-inspector/issues/585
> Fall back to memory caching if local storage is inaccessible

- ember_debug/libs/glimmer-tree.js
- Application outlet is no longer at the top of the tree.
- Layout meta was moved so template name was broken.
Fixes https://github.com/emberjs/ember-inspector/issues/605
> [GLIMMER] Fix application outlet state and templates

- ember_debug/object-inspector.js
Clicking the '$E' now also prints the name of the object sent to console along with the object for easier identification and clarity, resulting in more helpful output.
It does so by making use of the `inspect` function
Looks like this:- 
- includes a controller, route and a model
> '$E' now also prints the name of object sent to console.

- ember_debug/route-debug.js
> Avoid errors for router.router.recognizer.names as Object.create(null)

- README.md
Adds `bower install` to the Opera directions, as it is necessary and included in the installation instructions for Chrome and Firefox.
> Opera Add Bower Install

- package.json
It seems like since moving to a table based `x-list`, the scroll
container for vertical collection didn't have the proper height to allow
rendering all the components.
Fixes #648
> Add ember-cli-sass to build CSS file

- app/components/action-checkbox.js
- app/components/date-property-field.js
- tests/acceptance/object-inspector-test.js
- tests/acceptance/route-tree-test.js
- tests/ember_debug/object-inspector-test.js
- tests/ember_debug/view-debug-test.js
Before removing jQuery in the inspector itself, we have to update ember and ember-cli to 2.13
Since this repo is a bit unidiomatic, I might use some help with that.
@teddyzeenny Is there a reason for the inspector to be on an old version?
> Remove all usages of jQuery in tests

- ember_debug/libs/glimmer-tree.js
> Fix #625 skip building outlet tree, if controller doesn't exist

- ember_debug/view-debug.js
This folder is the one that actually runs along with the user's app, so in
theory this is enough to make the inspector work on apps without jQuery.
However in following PRs I'd like to completely remove jQuery from the
extension and ensure tests are run without it, so nobody inadvertently
reintroduces it by mistake.
> Remove all usage of jQuery from `/ember_debug` folder.

- ember_debug/adapters/chrome.js
Fixes the inspector on apps that disable prototype extensions.
cc @cibernox
> Object.assign cannot perform a deep clone like jQuery.extend

- app/components/x-list-content.js
Instead let's just append the event to the right child and let events
work normally
Closes #697
> Don't rely on checking the tagname of the event target

- app/styles/mixin.scss
- ember_debug/object-inspector.js
Some mixins' `toString` just prints the entire function - so we don't let it wrap.
Before:
After:
> Don't let mixin names wrap in the object inspector

- ember_debug/data-debug.js
This is a regression caused when we moved to ES6 arrow functions
> Fix unloading a record in the data tab

- app/components/x-list-content.js
This was working accidentally because Chrome sets the `event` global to the current event.
It breaks in FF thankfully, which allowed me to catch it.
> Fix event variable name

- ember_debug/view-debug.js
In Chrome 61, they add a new property `toJSON` in ClientRect.
After we have a $.extend({}, rect), the `toJSON` property becomes
an ownProperty.
This will break the code `$(div).css(rect)`.
The fix is to delete that toJSON property
> Fix a issue for Chrome 61

- app/controllers/view-tree.js
- app/templates/view-tree-toolbar.hbs
- app/templates/view-tree.hbs
- tests/acceptance/view-tree-test.js
When dealing with a complicated view tree, it can be cumbersome scrolling through all the views trying to identify the one that is of interest.
To help make finding it easier I added an input field to filter the list that is visible in the scroll view.
It naively looks for the substring to be present in the name of the view to determine a match.
The filter also works with the components included in the view tree.
Demo:
Refs Issue https://github.com/emberjs/ember-inspector/issues/677
Looking for feedback around contribution guidelines, and if this solution fits the pattern being used in the application. Otherwise also accepting suggestions for improving the implementation.
> View tree search filter

- app/components/mixin-detail.js
- app/templates/components/mixin-details.hbs
Sort the properties of the selected mixin on the object-inspector sidebar.
Mentioned in this issue: https://github.com/emberjs/ember-inspector/issues/562
(I had some issues with tests, though running it against my Ember app, the properties were sorted correctly)
> Sort model properties

- app/adapters/chrome.js
Iframe was not working because of wrong context in callback.
> Fix Iframe detection.

- ember_debug/view-debug.js
The applicationView's selector was hard coded to `body > .ember-view`,
this does not work for applications that are not using body as their
rootElement. We need to respect rootElement.
> Fix emberApp's query selector

- skeletons/web-extension/background-script.js
```
Error in response to storage.get: TypeError: Cannot read property 'showTomster' of undefined
at Object.callback (chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/background-script.js:51:25)
at updateTabAction (chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/background-script.js:50:25)
at chrome-extension://bmdblncegkenkacieihfhpjfppoconhi/background-script.js:137:7
```
> prevent undefined options error

- skeletons/web-extension/manifest.json
Mozilla review requested to remove unsafe-eval. It seems we don't really need unsafe-eval for the inspector to function.
> Remove unsafe-eval from the csp

- app/controllers/model-types.js
- app/templates/model-types-toolbar.hbs
Resolve #741.
This is a bad PR in that it does not test the added functionality. I tried adding a test as you can see [here](https://github.com/efx/ember-inspector/tree/fix-741-broken-tests) but `moduleFor` blew up with
Given end of day before a break, I thought I'd just PR the functionality for whenever you get a chance to review. Thanks for the pointers in the issue. It made this trivial.
> preserve model type hiding

- .travis.yml
- app/templates/view-tree-toolbar.hbs
The magnifying glass was confusing me so I created an icon that is similar to the inspect icons in Chrome and Firefox.
Original:
New Chrome:
New Firefox:
> Update Inspect Views Icon

- app/styles/base.scss
- app/styles/nav.scss
- app/styles/split.scss
- ember_debug/view-debug.js
- The Lucida Grande font is feeling a bit dated, how about system fonts?
<details>
<summary>Font Screenshots</summary>
Original:
System font Mac/Chrome:
System font Mac/Firefox:
System font Ubuntu/Firefox:
(alignment of "components" label was not centered for me before the font change)
</details>
- I also tweaked the sidebar background color to match what I found in the latest Chrome.
- Last but not least, I tweaked the close button. I felt it was difficult to see and the "x" was way too chunky.
<details>
<summary>Close Button Screenshots</summary>
Old:
New:
</details>
> UI Tweaks to Match Latest Inspectors

- ember_debug/libs/glimmer-tree.js
I was trying running the dev mode of this and got errors on my site. I am assuming `getRoot` changed in Ember 3.1 or something in glimmer, but this should support both.
> Fix loading main outlet

- ember_debug/general-debug.js
- ember_debug/route-debug.js
- `emberCliConfig` was always false, using `getAttribute` instead of `attr` fixes the issue.
- From ember 2.7.0 the libraries are always found in `libraries._registry`, so we remove support for older versions.
- Documented `ember_debug/general-debug.js`.
> Fix file paths displayed in the Routes tab

- ember_debug/services/session.js
There seems to be a problem, in very specific circumstances, with the code that detects support for session storage:
To reproduce follow these steps:
1. On Google Chrome
2. Disable 3rd-party cookies
3. Open the browser inspector
4. Open on the Ember inspector
5. Visit a page showing an Ember app, on a frame
loaded from a different domain
It's important that the Ember inspector is already open when you land on the page (hence step 4 before 5). Reloading the iframe page with the Ember inspector open also reproduces the problem.
This PR appears to fix the problem for me.
> Avoid error in some environments

- .travis.yml
We need these branches to run in Travis for deployment.
> Add branches to build in Travis CI

- .eslintrc.js
- app/components/date-property-field.js
- app/components/drag-handle.js
- app/components/main-content.js
- app/components/property-field.js
- app/components/resizable-column.js
- app/components/x-list.js
- bower.json
- ember-cli-build.js
- package.json
- yarn.lock
Also had to switch to a new context menu plugin. This should get us closer to #590
> Remove jQuery from app

- app/components/drag-handle.js
- app/components/draggable-column.js
- app/components/x-list.js
- app/routes/application.js
- app/templates/-main.hbs
- app/templates/application.hbs
- app/templates/components/draggable-column.hbs
- app/templates/components/x-list.hbs
- app/templates/container-type.hbs
- app/templates/container-types.hbs
- app/templates/deprecations.hbs
- app/templates/info.hbs
- app/templates/model-types.hbs
- app/templates/promise-tree.hbs
- app/templates/records.hbs
- app/templates/render-tree.hbs
- app/templates/route-tree.hbs
- app/templates/view-tree.hbs
- package.json
- yarn.lock
Our builds are all failing now, due to ember-beta and ember-canary changes. I'm working to resolve some of the issues here, but if anyone knows of specific things I should be on the lookout for and definitely change, let me know!
cc @rwjblue @teddyzeenny
> [WIP] Trying to fix beta and canary

- app/styles/mixin.scss
- public/assets/svg/inspect.svg
See animated GIF below (ignore the colors).
Also made an adjustment to an SVG that was throwing an svg-jar warning in the command line.
> Sticky Mixin Headers

- README.md
Bower is not used anymore in this project. Removed the instructions to install bower dependencies.
> Remove references to bower in README

- app/components/item-types.js
- app/controllers/component-tree.js
- app/models/promise.js
- app/templates/component-tree-toolbar.hbs
- app/templates/components/item-types.hbs
- app/templates/container-types.hbs
- app/templates/model-types-toolbar.hbs
- app/templates/model-types.hbs
- ember_debug/mixins/port-mixin.js
- ember_debug/view-debug.js
Just some light refactoring to remove a bit of duplication
> Refactor duplication

- app/controllers/route-tree.js
- app/templates/route-tree-toolbar.hbs
- tests/acceptance/route-tree-test.js
https://github.com/emberjs/ember-inspector/issues/129
> Search Routes

- app/styles/mixin.scss
- app/styles/object_inspector.scss
https://github.com/emberjs/ember-inspector/issues/800
Flexbox was allowing the property key to push other elements out of the way.
> Object Inspector Large Key Name Fix

- ember_debug/libs/glimmer-tree.js
Closes #775 
I think it is okay to do this. It doesn't seem to effect other functionality.
cc @Bestra @Turbo87
> Fix rootElement.getAttribute error

- app/libs/promise-assembler.js
- app/libs/resizable-columns.js
- ember_debug/libs/promise-assembler.js
Attempted fix of #834. Not sure if I have to do something weird for the import in [`ember_debug/libs/promise-assembler.js`](https://github.com/emberjs/ember-inspector/pull/835/files#diff-c50ce0bdd9f93deddf67c4549ed160f6) or not…
> replace all uses of Ember.copy, Ember.merge w/ Object.assign

- app/controllers/component-tree.js
- app/routes/application.js
- app/routes/component-tree.js
- app/templates/component-tree.hbs
- ember_debug/main.js
- ember_debug/object-inspector.js
- ember_debug/view-debug.js
- skeletons/web-extension/background-script.js
- skeletons/web-extension/manifest.json
- tests/acceptance/component-tree-test.js
Features:
- Once the inspector is open and on screen, users can right click on an element and open it in the component tree via the context menu
- The component tree will scroll the relevant component into view.
This PR supersedes #788.  Closes #689
> Context menu item for inspecting components

- ember_debug/object-inspector.js
Resolves #791
I believe using Ember.get should fix this issue right @rwjblue?
It was this error:
```
Error message: Assertion Failed: You attempted to access the `_debugInfo` property (of <DS.PromiseObject:ember2256>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. **However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('_debugInfo')` in this case.**
```
> Use Ember.get to get _debugInfo

- ember_debug/general-debug.js
- ember_debug/main.js
- ember_debug/vendor/startup-wrapper.js
The primary difference between acceptance tests for Ember < 3 vs Ember >= 3 is that for Ember < 3, every test created a new application + one application instance, whereas in Ember > 3 all the tests use the same application, but a different application instance for each test. The inspector was relying on the application boot, (which only happens once during tests in Ember >=3, and it happens even before the first test starts which was causing the inspector to fail and throw errors as it was starting even before the first application instance was created).
On the plus side, making the inspector only boot on application instance boot (instead of on application boot) also works for prior versions, and feels more "correct", so this should resolve everything everywhere.
Resolves #816 
Resolves …
> Fix Ember Inspector during tests for Ember >= 3

- app/components/route-item.js
- app/controllers/route-tree.js
- app/routes/route-tree.js
- app/utils/check-current-route.js
- ember_debug/route-debug.js
- testem.js
- tests/acceptance/route-tree-test.js
- tests/unit/check-current-route-test.js
> Fix routes reset namespace display

- app/controllers/model-types.js
- app/templates/model-types-toolbar.hbs
- app/templates/model-types.hbs
- app/utils/local-storage-keys.js
- tests/acceptance/data-test.js
It would be nice to be able to sort models by their record count as well as alphabetically (current option).
- Adds ability to sort models by record count
- Adds test for new sort functionality
- DRYs up the code to get, set, and remove  model sorting keys from Storage
> Add ability to sort models by record count

- ember_debug/view-debug.js
This should exclude liquid-fire elements or various others that add classes to the application container ember-view.
If you were adding your own classes to the application container, this would break, but I think this supports the majority of cases, and application wrappers are disabled by a lot of people these days anyway.
Resolves #419
@emberjs/inspector what do you guys think of this? It would hide liquid-fire etc from the view tree, but I think that is okay?
> Use [class='ember-view'] selector to exclude anything with extra classes

- app/components/mixin-detail.js
- app/components/mixin-details.js
- app/components/mixin-property.js
- app/components/object-inspector.js
- app/styles/object_inspector.scss
- app/templates/components/mixin-details.hbs
- app/templates/components/mixin-property.hbs
- app/templates/components/object-inspector.hbs
- ember_debug/object-inspector.js
- tests/acceptance/object-inspector-test.js
https://github.com/emberjs/ember-inspector/issues/364
> Flat Display of Object Properties

- .travis.yml
- tests/ember_debug/promise-assembler-test.js
We need to allow beta and canary to fail, until we can find a way to run all Inspector tests as part of Ember PRs.
> Fix test failures by passing function references to `off`

- .stylelintrc.js
- app/styles/app.scss
- app/styles/base.scss
- app/styles/colors.scss
- app/styles/component_tree.scss
- app/styles/context_menu.scss
- app/styles/drag_handle.scss
- app/styles/dropdown.scss
- app/styles/ember-table.scss
- app/styles/error_page.scss
- app/styles/external_link.scss
- app/styles/list.scss
- app/styles/mixin.scss
- app/styles/nav.scss
- app/styles/notice.scss
- app/styles/object_inspector.scss
- app/styles/pill.scss
- app/styles/send_to_console.scss
- app/styles/sidebar_toggle.scss
- app/styles/split.scss
- app/styles/toolbar.scss
- app/styles/warning.scss
- app/styles/whats-new.scss
- package.json
- yarn.lock
I'm using styleline-config-ship-shape here, but open to other configs, if we don't want this one. One of the main changes to note is things are alphabetized.
> Enforce stylelint

- skeletons/web-extension/manifest.json
- skeletons/web-extension/options.js
This PR removes a chrome manifest warning (visible when loading the unpacked extension produced by the steps in the readme) by removing an obsolete `browser_style` property from the top level `options_ui` hash:
Per [the docs](https://developer.chrome.com/extensions/options#embedded_options) this property is no longer used, removing it has no effect as the default when specifying the options menu using [`options_ui`(embedded)](https://developer.chrome.com/extensions/options#embedded_options) - as opposed to simply [`options_page`(full page)](https://developer.chrome.com/extensions/options#full_page) - is this "modal" style options dialog:
There is also the option top explicitly set the `options_ui.open_in_tab` property to false. Would we prefer to be explicit or rely on the default here? …
> Clean up unused manifest property + prevent error in storage lookup

- app/styles/ember-table.scss
Fixes: https://github.com/emberjs/ember-inspector/issues/900
- Table heading bg color
- Cell hover
- Striped rows
\*  blue/orange differences are not part of this PR. *
Old:
New:
> Data Table Colors Fixens

- app/routes/component-tree.js
- app/routes/view-tree.js
- ember_debug/libs/glimmer-tree.js
Refactored the component tree route to extend the view tree route, since they had a lot of duplication. I also fixed an issue with `_targetObject` being removed, and we are now additionally checking for `_target`
Fixes #915
> Use `_target`, remove some duplication

- ember_debug/vendor/startup-wrapper.js
- tests/acceptance/app-picker-test.js
> use map for broader compatibility

- app/index.html
- skeletons/bookmarklet/load_inspector.js
- tests/index.html
The bookmarklet was not loading a theme so I added one to `app/index.html`. If Inspector is loaded in a browser extension `app/adapters/web_extension.js` will override based on browser chrome settings.
> Default theme for bookmarklet and tests

- app/routes/launch.js
- app/routes/libraries.js
- ember_debug/adapters/web-extension.js
- ember_debug/container-debug.js
- ember_debug/deprecation-debug.js
- ember_debug/port.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/route-debug.js
- tests/ember_debug/object-inspector-test.js
Fixes https://github.com/emberjs/ember-inspector/issues/950
> Remove usage of chainable functions .readOnly()

- app/controllers/deprecations.js
- app/templates/deprecations-toolbar.hbs
- ember_debug/deprecation-debug.js
Fixes #857 
This adds a checkbox (to the Deprecations tab) to bubble up deprecations to `ember-deprecation-workflow`. Toggling allows you to call `deprecationWorkflow.flushDeprecations` and have it work properly.
> Bubble up deprecations for ember-deprecation-workflow (#857)

- ember_debug/adapters/web-extension.js
`_channel` was previously a computed. We moved to setting it in `init`, but calling super first was triggering sending a message that tried to use `_channel` and it was not already set. This PR ensures we set it before calling super.
> Fix setting _channel by moving before super call

- ember_debug/container-debug.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/mixins/port-mixin.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/route-debug.js
- ember_debug/view-debug.js
This fixes a bug with the new application switcher functionality where `this.get('port')` was not set at times other code was trying to use it.
I removed the `port: readOnly('namespace.port')` in all the things that use the `port-mixin` and set the property in the init method of the mixin itself instead.
> [port] Change the way we set up the port property to be used by logic in the port-mixin

- app/styles/component_tree.scss
- public/assets/svg/disclosure-triangle.svg
**Trying to click a 9x9 svg is madness.**
Before _(gray background for illustration)_:
After _(gray background for illustration)_:
> Increase size of click area of component tree disclosure triangle

- package.json
This drops support for Ember < 3.4.0 in master. The published inspector will still support Ember versions back to 1.0.0 but will open up older inspectors depending on which Ember version the app is on.
I also bumped the inspector minor version to 3.11.0 on master following the 3.10.0 release.
- Ember Inspector v1.10.0 (supports Ember v1.0.x -> v2.6.x): commit to branch [ember-0.0.0-2.7.0](https://github.com/emberjs/ember-inspector/tree/ember-0.0.0-2.7.0) and re-upload it using `yarn lock-version`.
- Ember Inspector v3.10.0 (supports Ember v2.7.x -> v3.3.x): commit to the branch [ember-2.7.0-3.4.0](https://github.com/emberjs/ember-inspector/tree/ember-2.7.0-3.4.0) and re-upload it using `yarn lock-version`.
Finally build and release a new version of the main inspector which will include …
> Drop support for Ember versions < 3.4.0 in master

- app/helpers/classify.js
- app/helpers/console.js
- app/styles/component_tree.scss
- app/templates/components/component-tree-item.hbs
- tests/acceptance/component-tree-test.js
> Component Tree: Angle Brackets and Classified Names

- ember_debug/main.js
- ember_debug/render-debug.js
- ember_debug/utils/render-utils.js
- ember_debug/view-debug.js
I started renaming and commenting things and trying to split things out a bit. Hopefully this is step one of many of making this easier to follow!
> Refactor render debug

- package.json
- yarn.lock
Bump to Ember Inspector 2.1.0. I don't think there are major fixes associated with bump that apply here (most recent fixes are around selection) but the row buffer is dropped to 0 upstream which makes things feel snappy.
And in general it gets off the pinned SHA.
I did smoke test this locally in addition to running the suite. Looks good.
We need a new beta of `vertical-collection` to be released since the `yarn.lock` now has both a SHA and version pinned which is a bit messy.
> Upgrade to Ember Table 2.1.0

- ember_debug/object-inspector.js
Fixes #1004
`!= null` checks for both `null` and `undefined`. It's faster than simply `if (object)`.
> Guard against reading a property on undefined, fixes #1004

- ember_debug/utils/type-check.js
Fixes https://github.com/emberjs/ember-inspector/issues/999.
`getDescriptorFor()` returns undefined for certain properties ( like computed properties through _ember-redux_, for example), so wrap it with a logical OR to prevent the _dependentKeys accessor from throwing an exception.
> Add undefined check for getDescriptorFor()

- app/components/route-cell-name.js
- app/controllers/route-tree.js
- app/templates/components/route-cell-name.hbs
- app/templates/components/route-cell-objects.hbs
- app/templates/components/route-cell-template.hbs
- app/templates/components/route-cell-url.hbs
- app/templates/route-tree-toolbar.hbs
- app/templates/route-tree.hbs
> Modernize Route Tab

- app/utils/search-match.js
- tests/acceptance/component-tree-test.js
- tests/unit/utils/search-match-test.js
https://github.com/emberjs/ember-inspector/issues/1021
> Ignore dashes in search

- app/controllers/container-type.js
- app/controllers/container-types/index.js
- app/templates/components/item-types.hbs
- app/templates/container-type-toolbar.hbs
- app/templates/container-type.hbs
- app/templates/container-types.hbs
- app/templates/container-types/index-toolbar.hbs
- app/templates/model-types.hbs
`this, {{on}}, < />, action` etc.
> Tidy up container tab

- app/controllers/promise-tree.js
- app/templates/components/promise-item.hbs
- app/templates/promise-tree-toolbar.hbs
- app/templates/promise-tree.hbs
> Tidy up Promise tab

- app/helpers/classify.js
- ember_debug/view-debug.js
Hey all, first PR to this repo 👍 
This PR updates the display of component names to use `::` instead of `/`, so that it matches the [Angle Bracket Nested Invocation RFC](https://emberjs.github.io/rfcs/0457-nested-lookups.html)
In addition, this updates the component names used when "Inspecting" components so that they also match this syntax.
Before:
After:
> Use "::" instead of  "/" when displaying component names

- app/components/object-inspector/property.hbs
- app/components/object-inspector/property.js
- app/components/object-inspector/sort-properties.js
- app/routes/application.js
- app/styles/colors.scss
- app/styles/object_inspector.scss
- app/templates/components/object-inspector.hbs
- ember_debug/object-inspector.js
- ember_debug/promise-debug.js
- ember_debug/utils/type-check.js
- tests/acceptance/object-inspector-test.js
- tests/ember_debug/object-inspector-test.js
* Dont use observe for update properties
* Add icons for tracked, function, getter
* support computed that return undefined
* sort and group properties by type. 
Service -> Tracked -> Computed -> Getter -> Property -> Function
* support complex getters, can always be calculcated when needed
* include functions, (why not?)
> Support tracked and other improvements

- app/adapters/web-extension.js
- app/routes/component-tree.js
- ember_debug/adapters/web-extension.js
- skeletons/firefox/lib/devtools-utils.js
- skeletons/firefox/lib/tomster-devtool-panel.js
This renames the `inspectDOMElement` API to `inspectDOMNode`, and changes the argument from a CSS selector to an XPath selector.
The problem with CSS selectors are that they only support selecting elements, whereas XPath allows us to select any arbitrary DOM node, including text nodes, comments etc.
This commit sets a better foundation for supporting things other than classic components. Since Glimmer components, route templates, "tagless" classic components etc have "outer HTML" semantics, they don't necessarily have a single element. Going forward, we will likely want to select the first node in a component's "bounds", which could be an arbitrary DOM node (i.e. may or may not be an element node, so CSS selectors are not sufficient).
> Use XPath to select elements

- app/controllers/component-tree.js
- app/routes/component-tree.js
- ember_debug/libs/glimmer-tree.js
- ember_debug/view-debug.js
- tests/acceptance/component-tree-test.js
- tests/ember_debug/view-debug-test.js
The inspector used to support filtering out components in the view tab, and there are a lot of supporting code for that. Since the view tab was removed, there is no longer any way to set this option, and it is always true in practice.
> Remove unused code

- .github/workflows/build.yml
This ensures we will always have the artifacts to easily test PRs using the "load unpacked" method, or for manual publishing.
> Always run the "Build extensions" step

- .github/workflows/build.yml
- README.md
> Auto publish

- .github/workflows/build.yml
This should have been included in #1080, it was needed for the npm publishing step.
> Add missing npm artifact

- .github/workflows/build.yml
Even though the documentation seem to suggest that the option can be passed as an environment variable, it didn't work.
> Fix Chrome publishing

- skeletons/web-extension/background-script.js
Electron's Chromium doesn't have `chrome.contextMenus`, so this code was throwing an error and preventing the inspector from working.
> Fix inspector in Electron

- ember_debug/libs/glimmer-tree.js
- tests/ember_debug/view-debug-test.js
This hasn't been working for a while
> Fix template name

- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
set the names of known mixins
remove properties set by mixins unless different value
causes them to hide the class with only merged mixins from Object.extend(mix1, mix2)
> Name Known Ember Mixins

- app/components/app-picker.js
- app/initializers/setup.js
- app/services/port.js
- tests/acceptance/app-picker-test.js
- tests/acceptance/component-tree-test.js
- tests/acceptance/container-test.js
- tests/acceptance/data-test.js
- tests/acceptance/deprecation-test.js
- tests/acceptance/info-test.js
- tests/acceptance/object-inspector-test.js
- tests/acceptance/promise-test.js
- tests/acceptance/render-tree-test.js
- tests/acceptance/route-tree-test.js
- tests/helpers/trigger-port.js
This is more idiomatic, and allows things like `@service port;` to work.
> Refactor app `port` into a regular service

- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
call getter directly
Ember.get auto tracks properties is seems, breaking the tracked detection.
So, it marks Getters as tracked, if the getter does not depend on any tracked property,
> Fix tracked detection

- .github/workflows/build.yml
yarn pack will remove the leading zeros from months and days when making the version string, so we need to make sure that the generated tar matches that.
I have address both the day and the month so we should be good when January rolls in.
> Do not include leading zeros when calculating version number

- ember-cli-build.js
- lib/ui/index.js
- lib/ui/package.json
With ember-cli-htmlbars 4.2, there is a check to disable co-location support on old ember versions (which, even when compiled, would fail at runtime due to missing `setComponentTemplate`). This is causing build failures when running ember-try with old Ember versions. Since we don't actually run the app or its tests in ember-try, we can work around the problem by skipping template compilation for now.
Paired with @rwjblue
> Avoid errors when using older Ember versions.

- tests/ember_debug/object-inspector-test.js
A new version of the `eslint-plugin-ember` caught a few more cases in this file. Since it's intentional here, we should just disable the rule for the whole file.
> Fix no-new-mixins

- app/components/list.js
- app/controllers/model-types.js
- app/controllers/render-tree.js
- app/routes/launch.js
- app/services/storage.js
- app/services/storage/local.js
- app/services/storage/memory.js
- app/utils/local-storage-keys.js
- tests/acceptance/data-test.js
- tests/test-helper.js
Ensure we are always using the in-memory storage service backend in tests, so that we aren't leaking test states into local storage, or otherwise change test behaviors due to existing items there.
> Refactor `StorageService`

- app/adapters/basic.js
- app/components/app-picker.js
- app/controllers/component-tree.js
- app/controllers/deprecations.js
- app/initializers/setup.js
- app/routes/app-detected.js
- app/routes/application.js
- app/routes/component-tree.js
- app/routes/deprecations.js
- app/services/port.js
- app/templates/components/app-picker.hbs
- ember_debug/adapters/basic.js
- ember_debug/main.js
- ember_debug/vendor/startup-wrapper.js
- tests/acceptance/app-picker-test.js
- tests/acceptance/component-tree-test.js
- tests/acceptance/container-test.js
- tests/acceptance/data-test.js
- tests/acceptance/deprecation-test.js
- tests/acceptance/info-test.js
- tests/acceptance/object-inspector-test.js
- tests/acceptance/promise-test.js
- tests/acceptance/render-tree-test.js
- tests/acceptance/route-tree-test.js
- tests/acceptance/whats-new-test.js
- tests/ember_debug/view-debug-test.js
- tests/test-adapter.js
- tests/test-helper.js
The main goal is to get the tests to more accurately reflect what actually happen in real applications. Instead of mocking/reopening the application "port", we now directly replace the adapter with a `TestAdapter` that faithfully implements the required hooks the same way that a "real" adapter does.
This allows us to write acceptance tests by only sending/responding to messages in a way that is, as a far as the inspector app can is concerned, indistinguishable from the "real" ember debug behaves in the real world. The new API also allows us to be a bit more precise in terms of the expectations (messages sent/received the correct number of times, in the right order, etc).
Split from #1088. I'll rebase that PR and merge in these changes when this lands.
> Refactor acceptance tests

- app/adapters/web-extension.js
- app/routes/component-tree.js
- ember_debug/adapters/basic.js
- ember_debug/adapters/web-extension.js
- ember_debug/view-debug.js
A while ago we discovered the reason this dance was needed, so we documented the reason and simplified the implementation a little bit while we are at it.
Split from #1088. I'll rebase that PR once this lands.
> Update `inspectNode` implementation

- .github/workflows/build.yml
- config/ember-try.js
- config/environment.js
- ember_debug/adapters/web-extension.js
- tests/ember_debug/deprecation-debug-test.js
This adds a non-trivial amount of cost for each message (especially the complex ones like the view tree) that is not necessary in most apps.
Split from #1088. I'll rebase that PR once this lands.
> Only deepClone when without prototype extensions

- ember_debug/object-inspector.js
- ember_debug/utils/bound-method.js
- tests/ember_debug/object-inspector-test.js
Previously, the object inspector would schedule an infinite timer that fires every 300ms to update the current object (it actually fires even where there isn't a current object to update). This is extremely inefficient, and it causes a lot of extra work in big apps, since the timer starts a runloop which results in a full top-down revalidation. The more appropriate thing to do is tap into the runloop callbacks, since as far as Ember is concerned, if there are no runloops, there are no observable changes.
Split from #1088. I'll rebase that PR once this lands.
> Don't abuse timers

- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
- tests/ember_debug/view-debug-test.js
- tests/helpers/setup-destroy-ei-app.js
Glimmer components instead dev mode assertion getters to warn about mismatches between the Ember.js vs legacy Glimmer.js APIs. Skip these properties when inspecting them to avoid tripping them.
Split from #1088. I'll rebase that PR once this lands.
> Fix inspecting Glimmer components w/ obj inspector

- app/routes/whats-new.js
- config/environment.js
- tests/acceptance/whats-new-test.js
There are a few cases where the CHANGELOG on master may not match the version you are actually running. For example, master can be behind the stable branch's CHANGELOGs, or you could be loading and running a nightly version. This patch try to fetch the CHANGELOG from the correct Git tag to ensure things matches up correctly.
> Render the CHANGELOG for the current version

- package.json
- yarn.lock
Revert some dependencies bump from #1096 because `ember-electron` (probably the only npm consumer?) still support Node 8. This is mostly a technicality, since they don't actually run the build and only consume the artifacts in `dist` (included in the npm package).
We should probably find a better way for them to consume the app, but in the mean time, this will allow them to consume the latest inspector until Node 8 is officially EOL in a few weeks. We can try this again when Ember CLI drops Node 8 support (likely 3.17).
> Bring back Node 8 support (for now)

- app/styles/base.scss
- app/styles/colors.scss
- app/styles/component_tree.scss
- app/styles/utils.scss
- app/templates/components/component-tree-item.hbs
- tests/acceptance/component-tree-test.js
This PR addresses two issues:
1. Clipping of a component background color that extends past the list bounds
- This is addressed by adding a child element that has the same background color as the item
1. Component actions being hidden when the component extends past the list bounds
- This is addressed by using `position: sticky` on the actions to pin them to the right side.
---
ℹ️ All additions to `app/styles/utils.scss ` are based off of Tailwind.
> Fix component list overflow

- package.json
- tests/acceptance/data-test.js
- yarn.lock
The diff: https://github.com/Addepar/ember-table/compare/v2.1.3...v2.2.2
Would unblock Ember 3.15 among other minor fixes.
> Bump Ember Table to 2.2.2

- skeletons/web-extension/boot.js
Fix #1136.
I chose to whitelist the [HTML mime
type](https://www.iana.org/assignments/media-types/media-types.xhtml#text) only since it is simpler.
Per Godfrey's comment, we could declare [matching in the manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) but it does so by URL or protocol. Because of that I think checking the mime type in the document is simpler and more readable.
> only boot inspector on HTML pages

- .eslintrc.js
- .prettierrc.js
- app/controllers/component-tree.js
- app/helpers/component-argument.js
- app/helpers/is-string.js
- app/styles/colors.scss
- app/styles/component_tree.scss
- app/styles/utils.scss
- app/templates/components/component-tree-item.hbs
- app/utils/truncate.js
- lib/ui/addon/styles/_list.scss
- lib/ui/addon/styles/_split.scss
- tests/acceptance/component-tree-test.js
Rebasing seemed hard, so opening a new PR
> Add args to tree

- app/adapters/web-extension.js
- ember_debug/vendor/startup-wrapper.js
- skeletons/web-extension/content-script.js
- skeletons/web-extension/manifest.json
Closes #1120 
As @chancancode explained in #1120[1], the injected debug code previously did
too much work in order to report a version miss.
To help understand what went wrong, I'll give an abridged version of the
boot-up protocol, and how the fallback logic fits in.
1. The Ember inspector application boots up inside of a devtools iframe,
and injects the version of `ember_debug.js` for the latest version
of the Ember inspector.
2. `ember_debug.js` to become aware of any supported version of Ember,
and when that happens, it checks whether the version of Ember on the
current page is supported by the current version of `ember_debug.js`.
3. If it matches, everything proceeds as usual, and `ember_debug.js`
starts communicating with the inspector pane.
4. If it doesn't match, `ember_debug.js` …
> Fix fallback to old inspectors

- app/styles/app.scss
- app/styles/base.scss
- app/styles/component_tree.scss
- app/styles/deprecations.scss
- app/styles/dropdown.scss
- app/styles/ember-table.scss
- app/styles/mixin.scss
- app/styles/object_inspector.scss
- app/styles/utils.scss
- app/styles/whats-new.scss
- app/templates/application.hbs
- ember-cli-build.js
- lib/ui/addon/components/empty-message.hbs
- lib/ui/addon/components/error-page.hbs
- lib/ui/addon/components/toolbar-search-field.hbs
- lib/ui/addon/components/warning-message.hbs
- lib/ui/addon/styles/_list.scss
- lib/ui/addon/styles/_nav.scss
- lib/ui/addon/styles/_pill.scss
- lib/ui/addon/styles/toolbar/_radio.scss
- package.json
- tests/ember_debug/view-debug-test.js
- yarn.lock
- Tailwind uses normalize.css, we should too
- Set html font-size to `62.5%` so `1rem == ~10px`; makes rem sizes easier to grok
- I'll start using the new font-size utility classes in another PR
I've done a lot of clicking around and I don't see any visible changes to the text.
> Base font size and utility classes

- app/controllers/model-types.js
- app/templates/model-types-toolbar.hbs
- tests/acceptance/data-test.js
Add a button in data pane to enable user to inspect store and send it to console.
Would love some guidance as to what a good test would be since a lot of the end-to-end functionality seems to be stubbed out in other tests.
> [FEAT] Add inspect store button to data pane in Ember Inspector

- .github/workflows/build.yml
Code Climate uses the `GIT_COMMIT_SHA` and `GIT_BRANCH` environment variables for the reports.
> Fix code coverage report

- tests/acceptance/app-picker-test.js
- tests/acceptance/component-tree-test.js
- tests/acceptance/container-test.js
- tests/acceptance/data-test.js
- tests/acceptance/deprecation-test.js
- tests/acceptance/info-test.js
- tests/acceptance/object-inspector-test.js
- tests/acceptance/promise-test.js
- tests/acceptance/render-tree-test.js
- tests/acceptance/route-tree-test.js
- tests/acceptance/whats-new-test.js
- tests/test-adapter.js
While working on #1163, we encountered an issue with the test adapter, where unmet expectations (when you set up a `respondTo` for a test that was never triggered) did not cause the offending test to fail. Instead, they became unhandled promise rejections (i.e. "global errors") and fails the _next_ test that runs.
This is because we were using the `QUnit.{testStart,testDone}` hooks as if they were a global version of `{before,after}Each`. However, the global hooks are really intended for things like test reporters and runs too late to affect things like the pass or fail status of a test.
This commit introduces a `setupTestAdapter` function that uses the normal (not global) APIs so that the failures are attached to the correct test.
> Introduce `setupTestAdapter` hook

- app/components/app-picker.hbs
- app/components/deprecation-item.hbs
- app/components/object-inspector.hbs
- app/components/object-inspector/dependent-keys.hbs
- app/components/object-inspector/errors.hbs
- app/components/object-inspector/properties-all.hbs
- app/components/object-inspector/properties-grouped.hbs
- app/components/object-inspector/property.hbs
- app/components/promise-item.hbs
- app/components/route-cell-objects.hbs
- app/styles/deprecations.scss
- app/styles/dropdown.scss
- app/styles/mixin.scss
- app/styles/object_inspector.scss
- app/styles/route_tree.scss
- app/styles/utils.scss
- app/templates/component-tree-toolbar.hbs
- app/templates/component-tree.hbs
- app/templates/container-type-toolbar.hbs
- app/templates/container-types/index-toolbar.hbs
- app/templates/model-types-toolbar.hbs
- app/templates/route-tree-toolbar.hbs
- lib/ui/addon/components/send-to-console.hbs
- tests/acceptance/component-tree-test.js
- tests/acceptance/container-test.js
- tests/acceptance/data-test.js
- tests/acceptance/object-inspector-test.js
- tests/acceptance/promise-test.js
- tests/acceptance/route-tree-test.js
Moved a lot of styles from `app/styles` to functional classes.
(also moved a bunch of test selectors to `data-test`)
> More functional classes and data-test selectors

- .github/workflows/build.yml
This is a workaround to fix this backwards incompatible issue: https://github.com/actions/download-artifact/issues/30 that popped up in `download-artifact@v2` since this repo is pinned to `download-artifact@master` right now and assumes `v1` behavior.
We should probably refactor in the future to support the `v2` pipeline.
> fix: pin artifact-download to v1

- .eslintrc.js
- tests/ember_debug/view-debug-test.js
Enable the no-duplicate-imports rule.
https://eslint.org/docs/rules/no-duplicate-imports
> No duplicate imports lint rule

- .eslintrc.js
- app/controllers/promise-tree.js
- app/controllers/records.js
- app/models/promise.js
- ember_debug/route-debug.js
This MR aims to enable the lint rule `no-observer` back, in order to prevent anyone to use observer in the future.
I would prefer to have this rule enabled by default and disable linter when needed, so anyone is aware that observer usage is avoided when using them WDYT ?
> No observers lint rule

- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
getClassName already handles this case
> fix attrs/args - toString is undefined

- app/controllers/container-type.js
- app/templates/container-type.hbs
- tests/acceptance/container-test.js
This commit uses `<EmberTable>`'s sorting capabilities to sort container
instances alphabetically be default. A sort indicator is shown in the
column header, and the header can be clicked to reverse the sort.
This PR adds test coverage for sorting and converts the template and
tests to use `data-test-` selectors instead of `js-` css classes.
> Sort container instances alphabetically

- ember_debug/render-debug.js
- tests/ember_debug/container-debug-test.js
- tests/ember_debug/deprecation-debug-test.js
- tests/ember_debug/ember-debug-test.js
- tests/ember_debug/object-inspector-test.js
- tests/ember_debug/promise-debug-test.js
- tests/ember_debug/render-debug-test.js
- tests/ember_debug/route-debug-test.js
- tests/ember_debug/view-debug-test.js
- tests/test-helper.js
Adds a side effecting import to `tests/test-helper.js` to ensure that `ember-debug/main` can be imported/required eagerly in the test suite (and is not broken by a cycle).
Updates all lazy requires for `ember-debug` modules to ES module import statements.
> Ensure renderDebug is properly unregistered.

- tests/helpers/setup-destroy-ei-app.js
- tests/integration/components/basic-test.js
Prior to this change we could not run any tests that leveraged the `@ember/test-helpers` setup methods that ran _after_ the files in `tests/ember_debug/**/*-test.js`. This was because the `setupEIApp`/`destroyEIApp` helper functions would call `setApplication` (to get a pristine state for their own tests), but would not clean up after themselves (calling `setApplication` with the original value).
This change is a minimal patch to fix the fundamental issue (and adding a single integration test to the mix to ensure it doesn't regress), but a larger refactor is in order to simplify these setupEI/destroyEI test helpers.
Related to #1201
> Reset internal test helper state for EmberDebug tests.

- tests/ember_debug/view-debug-test.js
This leverages the `CallExpression` form of the inline `hbs` compiler so that we can provide a custom module name and avoid having to muck with the private internal state of the compiled template itself (e.g.  `__meta`).
This mechanism is exactly the same as what is used by `ember-cli-htmlbars` when compiling standalone templates, and is much more resilient to internal private API changes in Ember itself.
> Remove private API usage to set moduleName in view debug tests.

- .eslintrc.js
- ember_debug/container-debug.js
- ember_debug/data-debug.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/object-inspector.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/route-debug.js
- ember_debug/view-debug.js
This MR aims to fix the future `ember/no-mixins` error, while upgrading eslint-plugin-ember from 7.13.0 to 8.5.1.
Preferred to disable the lint on each occurence instead of disabling the rule globally, as we did for observers.
See related issue: https://github.com/emberjs/ember-inspector/issues/1197
And the rule documentation: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-mixins.md
> Prevent future ember/no-mixins eslint error

- ember_debug/object-inspector.js
I guess this should have been Object.prototype.toString
to check if an object defines its own toString or not.
Now we get `[Object object]` for glimmer components
> fix get class name

- .eslintrc.js
- app/components/object-inspector.js
- app/components/object-inspector/properties-all.js
- app/components/object-inspector/property.js
- app/components/object-inspector/sort-properties.js
- app/components/promise-item.js
- app/components/render-item.js
- app/controllers/render-tree.js
- ember_debug/adapters/basic.js
- ember_debug/adapters/web-extension.js
- ember_debug/adapters/websocket.js
- ember_debug/container-debug.js
- ember_debug/data-debug.js
- ember_debug/deprecation-debug.js
- ember_debug/libs/promise-assembler.js
- ember_debug/libs/source-map.js
- ember_debug/main.js
- ember_debug/mixins/port-mixin.js
- ember_debug/models/promise.js
- ember_debug/object-inspector.js
- ember_debug/port.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/route-debug.js
- ember_debug/view-debug.js
- package.json
- tests/ember_debug/object-inspector-test.js
- yarn.lock
This was basically just updating to latest eslint-plugin-ember and running `yarn lint:js --fix`. I did disable `no-get` for now because they didn't all fix, and I figured we could incrementally fix those later.
Closes #1197 
Closes #1216 
Closes #1217
> Update eslint-plugin-ember, fix lint

- ember_debug/object-inspector.js
`@glimmer/validator` only accepts a `Tag` instance as an argument but we are passing the object + property name (basically we are treating it like `tagForProperty`). Recent versions of ember-source
(that have updated versions of glimmer-vm) actually use the passed in arguments to return the revision so we are hitting an error (since the `object` we pass is not a `Tag`).
Fixes https://github.com/emberjs/ember-inspector/issues/1298
> Ensure `valueForTag` is passed an actual `Tag`

- ember-cli-build.js
- skeletons/web-extension/manifest.json
We got an email from mozilla that disabled the recent versions of the addon due to the inclusion of 'unsafe-eval' in the manifest. It was added in 9022a02 and my best guess is it's to workaround CSP issues in development since ember-auto-import's webpack config uses eval in dev mode by default (it doesn't do it in prod) and the commit didn't materially changed the way we use imports in the extension itself.
Turns out, the last time this came up, we just removed it from the manifest (#737) because the conclusion was that the way we use eval and more importantly the places we uses eval is not subject to the CSP anyway, so we don't actually need to add it in the manifest.
I don't have time to fully investigate this so in the meantime I disabled the use of eval in development just in case. If …
> [INTERNAL] Remove unsafe-eval in manifest.json (again)

- .github/workflows/build.yml
Fixes https://github.com/emberjs/ember-inspector/issues/1406.
beta/canary are failing because of the deprecations addressed by https://github.com/emberjs/ember-inspector/pull/1405 and https://github.com/emberjs/ember-inspector/pull/1400.
Since I have those PRs up I thought I'd keep them separate and rebase once this goes in. What do you think?
> update CI to use environment files instead of set-env

- app/components/list-cell.js
- app/components/list-content.js
- app/components/promise-item.js
- app/components/render-item.js
- app/components/route-cell-name.js
- app/components/scroll-container.js
- app/controllers/component-tree.js
- app/helpers/build-style.js
- ember_debug/libs/view-inspection.js
- ember_debug/route-debug.js
- lib/ui/addon/components/drag-handle.js
- lib/ui/addon/components/resizable-column.js
- package.json
- tests/acceptance/route-tree-test.js
- yarn.lock
Updates import paths for `htmlSafe` to use `@ember/template` instead of the deprecated `@ember/string` import.
Source: https://github.com/ember-cli/ember-rfc176-data/blob/master/mappings.json
> update htmlSafe imports to the current package

- ember_debug/libs/view-inspection.js
- ember_debug/route-debug.js
- ember_debug/utils/classify.js
- ember_debug/utils/dasherize.js
- tests/ember_debug/deprecation-debug-test.js
Due to the new deprecations introduced in the canary build, CI started failing.
This should address the problem.
This should unblock the open dependabot PRs.
> Fix canary build

- .github/workflows/build.yml
The Build and Publish action has been broken since last September. This PR fixes the [error](https://github.com/emberjs/ember-inspector/runs/2026942742?check_suite_focus=true
) in step `volta install chrome-webstore-upload-cli` by inserting `volta install node` before it.
A sample build with the fix is able to move past `volta install chrome-webstore-upload-cli` to the upload step.
https://github.com/steventsao/ember-inspector/runs/2037371567?check_suite_focus=true
> Migrate to volta-cli/action

- .dependabot/config.yml
Running dependabot too often creates a lot of noise in the commit logs, making it nearly useless to track actual progress.
Running it less often would reduce this problem (security updates still running immediately).
*emberjs/ember.js has already made this change, though I think they configured it via the UI, which is obviously also an option (actually it's even better than doing it via a file IMO).*
See: https://github.com/emberjs/ember.js/pull/18979#issuecomment-631864842
> Run dependabot less often

- ember_debug/adapters/basic.js
- ember_debug/adapters/web-extension.js
- ember_debug/adapters/websocket.js
- ember_debug/container-debug.js
- ember_debug/data-debug.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/libs/capture-render-tree.js
- ember_debug/libs/promise-assembler.js
- ember_debug/libs/source-map.js
- ember_debug/main.js
- ember_debug/mixins/port-mixin.js
- ember_debug/models/profile-manager.js
- ember_debug/models/profile-node.js
- ember_debug/models/promise.js
- ember_debug/object-inspector.js
- ember_debug/port.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/route-debug.js
- ember_debug/services/session.js
- ember_debug/utils/ember.js
- ember_debug/utils/type-check.js
- ember_debug/view-debug.js
follow up for https://github.com/emberjs/ember-inspector/pull/1535
related conversation https://github.com/emberjs/ember-inspector/pull/1535#discussion_r620522333
> ember lookup util

- skeletons/web-extension/background-script.js
@chancancode I have been unable to determine a way to programmatically open the devtools when clicking this context menu item, but this gets us one step closer by actually switching routes in inspector. Any ideas on how to open devtools to the Ember Inspector panel? I haven't been able to find anything about it.
> Change message type to switch to components route

- ember_debug/vendor/loader.js
Prior to this change, calling `requireModule('foo')` would **create** a `foo` module (with no exports) due to eager caching in the list of "seen" modules.
This means that code like this:
```js
let Ember;
try {
Ember = requireModule('ember')['default'];
} catch {
Ember = window.Ember;
}
return Ember;
```
Will properly fallback to `window.Ember` the first time, but all subsequent runs will end up finding a module and returning `{}`.
This addresses at least _part_ of https://github.com/emberjs/ember-inspector/issues/1595 (cannot confirm if it is fully resolved, due to raciness and testing timing).
> Ensure vendored loader does not cache missing modules.

- CHANGELOG.md
Format also changed, so that each changelog entry sub-heading is no longer a link. But I think that makes sense actually, so I haven't modified that.
There is a separate PR that has updated the regex to detect this new sub-heading format.
Somewhat related: https://github.com/emberjs/ember-inspector/pull/1578
> Move changelog heading to top

- app/services/adapters/basic.js
- ember_debug/vendor/startup-wrapper.js
Closes https://github.com/emberjs/ember-inspector/issues/1758
No idea if this is the best way of solving it.
But since we're moving away from the `Ember` global a change such as this seemed reasonable, and respects the existing code (this change is minimal), since `window.EmberInspector` already existed.
Deleted `Ember.EmberInspectorDebugger` altogether, since it's not used elsewhere and I cannot find any code in Github (across all projects) that rely on it.
https://github.com/search?q=EmberInspectorDebugger&type=code
> Don't rely on Ember.EmberInspectorDebugger

- .github/workflows/build.yml
The chrome-webstore-upload-cli package updated its command from "webstore" to "chrome-webstore-upload".
This should allow new versions to be published to the webstore.
> Update Chrome Publish Action to Use New Command

- .github/workflows/build.yml
The latest version of chrome-webstore-upload-cli uses optional chaining (?. syntax), which is not supported until Node 14 (without polyfills). Updated the publish-chrome action to use node 14. Left the other actions on 12 for now because I'm not too comfortable with github actions or this repo.
Note: I was unable to test this locally - I am not sure how to run/test GitHub actions on local, but I fairly certain this should work. 
I just really want to get the Chrome extension updated so that I can update our apps to 3.28 :)
> Update publish-chrome action to use node 14.X

- ember_debug/object-inspector.js
`[].any` is only available when the prototype extensions are enabled, which isn't the case in all Ember apps.
Closes #1812
> replace `[].any` with `[].some`

- README.md
Comming from a clean slate (fresh OS) I had to install `ember-cli` first, then run `yarn install` and finally I could `yarn build`. Otherwise this error occures:
```bash
❯ yarn build
yarn run v1.22.17
$ ember build
Cannot find module 'ember-cli-version-checker'
Require stack:
- /home/username/Dev/ember-inspector/lib/ui/index.js
- /home/username/.config/yarn/global/node_modules/ember-cli/lib/models/package-info-cache/package-info.js
- /home/username/.config/yarn/global/node_modules/ember-cli/lib/models/package-info-cache/index.js
- /home/username/.config/yarn/global/node_modules/ember-cli/lib/models/project.js
- /home/username/.config/yarn/global/node_modules/ember-cli/lib/utilities/get-config.js
- /home/username/.config/yarn/global/node_modules/ember-cli/lib/utilities/instrumentation.js
- …
```
> docs(readme): change order of installation hints

- ember_debug/vendor/startup-wrapper.js
Using `{ once: true }` in the listener seems to fix our infinite number of calls. Fixes #1634
> Force startup-wrapper logic to run less times

- app/components/object-inspector.js
Let's upgrade the object-inspector component to extend '@glimmer/component'
rather than '@ember/component'. While we're here, let's also upgrade the
component to use native JS syntax.
> object-inspector: migrate to glimmer component

- app/controllers/component-tree.js
- tests/acceptance/component-tree-test.js
Right now, the left and right arrow keyboard shortcuts will collapse and
expand the currently selected node in the component tree respectively.
It would be nice (and more consistent with devtools) if:
- the left arrow keyboard shortcut would jump to the parent node if the
currently selected node is already collapsed
- the right arrow keyboard shortcut would jump to the child node if the
currently selected node is already expanded
> component-tree: make left/right arrow nav in certain conditions (fixes #1537)

- app/components/object-inspector/properties-all.js
- app/components/object-inspector/properties-base.js
- app/components/object-inspector/properties-grouped.js
object-inspector: update prop classes to glimmer
Let's update the PropertiesBase component to extend from
@glimmer/component rather than @ember/component. While we're here, let's
update PropertiesBase and its child classes PropertiesAll and
PropertiesGrouped to use native JS syntax.
properties-all: fixup misspelling in var name
Let's rename 'shoulApplyCustomFilter' to 'shouldApplyCustomFilter' as
'shoul' is just a typo for 'should'.
> properties-base, properties-grouped, properties-all: octane/glimmer upgrade 

- app/components/list.js
Since Ember 3.27, using . to access run loop functions has been
deprecated, such as run.bind. Instead, we must import the value directly
from the module like so:
import { bind } from '@ember/runloop';
See the deprecated-run-loop-and-computed-dot-access rule in ember's
deprecation-app for more details.
n/a
> list: fixup dot access for run.bind deprecation

- app/routes/application.js
- app/routes/container-type.js
- app/routes/data/index.js
- app/routes/info-index.js
- app/routes/launch.js
- app/routes/model-type.js
- config/deprecation-workflow.js
The methods transitionTo and replaceWith of the Route have been
deprecated in order to reduce the API surface related to routing.
Instead, we should inject the Router Service and use its transitionTo()
method.
n/a
> deprecations: fix instances of routing-transition-methods

- .template-lintrc.js
- app/components/list-content.hbs
- app/components/list.hbs
- app/components/promise-item.hbs
- app/components/promise-tree-toolbar.hbs
- app/components/render-item.hbs
- app/templates/app-config.hbs
- app/templates/container-type.hbs
- app/templates/container-types.hbs
- app/templates/container-types/index.hbs
- app/templates/deprecations.hbs
- app/templates/libraries.hbs
- app/templates/model-types.hbs
- app/templates/promise-tree.hbs
- app/templates/render-tree.hbs
- config/deprecation-workflow.js
- tests/integration/components/component-tree-arg-test.js
It is currently possible to reference properties on a component without
a preceding `this`. This style of looking up properties is known as
"property fallback", and has the potential to collide with other types
of values. The alternative way to lookup properties is with a preceding
`this`. This style does not have any ambiguity, since it's clear that
we're looking up the property on this instance of the component, and not
the global helper/component. Property fallback has been deprecated in
favor of this style in general.
As such, let's work through all of our templates in order to eliminate any
instances of this issue. Finally, let's stop silencing violations of this
deprecation in our deprecation-workflow config file. This will ensure that
future violations are not added to the …
> deprecations: resolve instances of this-property-fallback

- ember_debug/object-inspector.js
This mixin triggers a deprecation warning in Ember 3.28 applications.
Closes #1939
> Remove support for the TargetActionSupport mixin

- .eslintrc.js
Due to how qunit unloads a test module, importing a test file will cause
any modules and tests within the file to be executed every time it gets
loaded.
The no-test-import-export eslint rule will help us avoid this by
checking for any imports or exports from *-test.js files.
As we don't have any outstanding issues of this nature, let's go ahead
and re-enable the rule so that the linter will help us avoid adding any
going forward.
n/a
> eslintrc: enable no-test-import-export rule

- .eslintrc.js
As of Ember Octane, the actions hash and {{action}} modifier and helper
are no longer needed.  We should instead use the @action decorator or
`foo: action(function() {}))` syntax instead.
Right now, we've disabled the 'no-actions-hash' eslint rule. We do not
currently have any issues of this nature, so let's go ahead and
re-enable the rule so that the linter will warn us against creating new
issues of this type going forward.
n/a
> eslintrc: enable 'no-actions-hash' lint rule

- .template-lintrc.js
Right now, we disable the 'table-groups' linting rule. This rule helps
to ensure that table rows are grouped into one of: thead, tbody, tfoot,
helps avoid relying upon a (possibly to be deprecated) feature of
glimmer that auto-inserts these tags, and enforces that children of
<table> are ordered correctly. As such, it would be ideal to have this
enabled.
We don't have any outstanding issues that would cause errors to be
thrown by the linter by enabling this, so let's go ahead and do so.
n/a
> template-lintrc: enable 'table-groups' rule

- tests/ember_debug/object-inspector-test.js
Right now, when we run the 'Views are correctly handled when destroyed
during transitions' test from the 'Ember Debug - Object Inspector'
suite, there is a deprecation logged along the lines of:
Passing the `@class` argument to <Input> is deprecated. Instead,
please pass the attribute directly, i.e. `<Input class={{...}} />`
instead of `<Input @class={{...}} />` or `{{input class=...}}`.
Let's fix this deprecation by preferring angle bracket syntax for the
input component. This will help avoid having an unnecessary deprecation
show up in the test output.
n/a
> object-inspector-test: fix legacy-attribute-arguments issue

- tests/ember_debug/route-debug-test.js
Right now, the 'Route tree' test from the 'Ember Debug - Route Tree' has
a race condition between receiving the 'view:renderTree' message and
triggering 'route:getTree'.
The 'view:renderTree' message is sent after a 250ms debounce once a tree
is finished being profiled by the ProfileManager, so settled() isn't
going to be able to cover that operation.
To work around this, let's waitUntil we receive the 'view:renderTree'
message before proceeding with our test. This is fairly similar to how
this message is waited for in the view-debug-test suite.
n/a
> route-debug-test: avoid 'view:renderTree' race condition

- skeletons/web-extension/background-script.js
It wasn't working. This triggers contextMenu in the ember_debug app and selects the nearest component. There is no way to programmatically open devtools. There is experimental api for it. But then it cannot be put into the market
> bring back the inspect component context menu functionality

- app/services/adapters/web-extension.js
- ember_debug/vendor/startup-wrapper.js
* sometimes initializers already run or a deferReadiness exists, but still no instance ready. with _bootPromise and didBecomeReady we can ensure that we continue loading
* all requireModule which try to load ember related modules would fail in some cases of some race conditions.
this happens when ember inspector was already opened and the app is reloaded. (e.g. during development). in that case it can happen that ember_debug is loaded before ember. It would use the requireModule provided by ember_debug instead of the ember provided one.
* Without the setTimeout, onEmberReady will do a requireModule('ember') while ember is still loading inside the define. So it's state is not finalized and then ember and onEmberReady will run multiple times. …
> fix loading ember-inspector after reload

- ember_debug/libs/view-inspection.js
when selecting a component on the webpage, e.g via context menu. a tooltip will show in the website highlighting the selected component.
after clicking outside the tooltip or clicking escape it will hide the tooltip on the webpage and also the object inspector in the ember inspector.
Hiding tooltip is enough. Keep inspector open so i can debug my app, interact with my app and see changes directly in ember-inspector/ object inspector
fixes #2013
> do not close the object inspector

- scripts/download-panes.js
This removes our dependence on S3 and downloads the panes directly from a GitHub branch
> Download panes from GitHub instead of S3

- ember_debug/object-inspector.js
also check for Function prototype.toString
its now different from Object.prototype.toString as its overwritten by core-js...
https://github.com/zloirock/core-js/blob/master/deno/corejs/index.js#L1195
> fix class names in object inspector

- app/services/adapters/web-extension.js
- ember_debug/utils/ember/debug.js
- ember_debug/vendor/startup-wrapper.js
- skeletons/web-extension/content-script.js
- skeletons/web-extension/manifest.json
chrome.devtools.inspectedWindow.eval(emberDebug, { frameURL: url }) does not work for iframes without a src
fixes #868
> fix iframes without src, e.g. twiddle

- app/components/scroll-container.hbs
- app/components/scroll-container.js
- app/controllers/component-tree.js
- app/templates/component-tree.hbs
this makes the component tree view scroll the previewing or selected component into view.
This is when previewing components on the page or selecting them via the context menu on the page
I also made sure that it only scrolls one time to the current item
> scroll into view while previewing or selecting from page

- ember_debug/libs/render-tree.js
- ember_debug/object-inspector.js
- tests/ember_debug/view-debug-test.js
fixes #1536, fixes #1387
shows args for template only components in the object inspector
> show args for template only components

- ember_debug/libs/render-tree.js
- tests/ember_debug/view-debug-test.js
just noticed that the objects in the args had only an id as it was serialized. no need to serialize args at this point
> fix args of template only components

- ember_debug/libs/render-tree.js
for components that did not render anything. e.g. everything inside an `if`
> getRange might return null

- ember-cli-build.js
e.g. render performance page did not load and possibly other issues
because chunks of webpack where not loaded since url was wrong
https://github.com/ef4/ember-auto-import/issues/540
> fix some pages not loading

- app/services/port.js
there isban issue in tests where off is called before it was setup, causing inspector to become unresponsive.
another way would be to setup a deactivate listener after setting up the port listener.
e.g.  
```
this.port.one('general:reset', this, this.reset);
this.one(this, 'deactivate', () => this.port.off('general:reset', this, this.reset))
```
> fix evented off 

- app/services/adapters/basic.js
- app/services/adapters/web-extension.js
- skeletons/web-extension/background-script.js
- skeletons/web-extension/content-script.js
this is probably better and safer than window messaging
> use internal messaging to setup iframes

- app/components/object-inspector/dependent-keys.hbs
- app/styles/object_inspector.scss
- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
in earlier versions of ember, tags had an _propertyKey which was used to show some tracked dependencies of getters. this brings it back for current versions.
in addition I tried to improve the way its displayed
> bring back tracked dependencies

- app/components/object-inspector/sort-properties.js
- ember_debug/object-inspector.js
Also, put the length property at the top
> Fix more items indicator sometimes not appearing

- skeletons/web-extension/content-script.js
fixes #2243 
with this it wont be intercepted by the wordpress editor
> add script tag to the head instead

- ember_debug/object-inspector.js
- tests/acceptance/object-inspector-test.js
- tests/ember_debug/object-inspector-test.js
- tests/ember_debug/view-debug-test.js
Fixes known issue #2237.
If a property name includes a `.` such as in `{ 'property.name': 123 }`, the value is now accessed using bracket notation instead of `get()` in order to treat the name as a string literal and avoid attempting to access a nested value.
If a property name does not include a `.`, there is no change in functionality.
A test was added to ensure the correct value is accessed given this scenario.
> fix: Use correct value path in object inspector (#2237)

- ember_debug/object-inspector.js
that seems to be the preferred way to require throughout the rest of the app
> use requireModule instead of require

- package.json
- pnpm-lock.yaml
current builds do not have svgs because of an issue in older ember-svg-jar version
> fix no svgs

- ember_debug/libs/render-tree.js
- ember_debug/libs/view-inspection.js
- ember_debug/object-inspector.js
- ember_debug/utils/ember-object-names.js
- ember_debug/utils/get-object-name.js
- package.json
- pnpm-lock.yaml
- tests/ember_debug/view-debug-test.js
this injects a InElement component into the component tree, which has its bounds set to the target. it also adds it as a root tree element, so the click & hover work correctly.
This is also done for EmberWormhole, the code checks for the EmberWormhole instance and changes the bounds to its target element
resolves #1255 
closes #1375
> support in-element & wormhole

- ember_debug/libs/view-inspection.js
limit width of tooltips and clips too long content.
On hover it will show the full string as tooltip, via title attribute
> limit max width of tooltips

- ember_debug/libs/view-inspection.js
follow up of #2426 
Forgot to revert this...
> remove title

- app/services/adapters/web-extension.js
- ember-cli-build.js
- skeletons/web-extension/boot.js
- skeletons/web-extension/content-script.js
- skeletons/web-extension/manifest.json
- skeletons/web-extension/scripts/boot.js
> fix manifest

- ember_debug/libs/promise-assembler.js
> fix .get is not defined

- ember_debug/general-debug.js
emberCliConfig was overriden to null,
caused during modernization
> [app-info] fix missing app config

- ember_debug/libs/view-inspection.js
- tests/ember_debug/view-debug-test.js
sorry for pr again...
found this issue when a small component is at the right side
> use word-wrap and add line break controls

- ember_debug/utils/ember.js
switched up some things.
this is used here only:
https://github.com/emberjs/ember-inspector/blob/main/ember_debug/utils/ember-object-names.js 
the result is that the names for those are now marked as unknown
> fix some ember names detection

- skeletons/web-extension/manifest.json
From what I can tell, we need to add a unique id for the extension when using manifest v3 with Firefox. This should accomplish that goal.
> Add id for manifest v3 support in Firefox

- ember-cli-build.js
- ember_debug/libs/source-map.js
- ember_debug/utils/type-check.js
- package.json
- pnpm-lock.yaml
I wanted to load the source map from node_modules. but that wasnt working properly. 
Currently its not possible to trace in console for deprecations.
Also fixes #2491
Probably, it's the only place that actually could call `require` in certain conditions.
All others use `requireModule`
> switch to source-map-js

- ember_debug/vendor/loader.js
Some could overwrite these with their own implementation.
we can always use requireModule only
> make amd safe

- ember_debug/data-debug.js
Just use filter directly 
fixes #2502
> fix inspecting ember data records

- ember-cli-build.js
- skeletons/web-extension/boot.js
- skeletons/web-extension/manifest.json
- skeletons/web-extension/scripts/boot.js
this does not work for firefox
```
Reading manifest: Warning processing content_scripts.0.world: An unexpected property was found in the WebExtension manifest.
```
Also has warnings about permissions
but firefox keeps the order right for script loading
it needs to run before everything else so that ember gets the debug config. If the property is set later, component tree will not work.
this issue only happens on page refresh, then browser uses cached data and immediately runs the scripts, without waiting for the new script that have been added by extensions. this does not happen in firefox, only chrome.
https://bugs.chromium.org/p/chromium/issues/detail?id=634381
fixes #2500
> correctly load scripts in chrome & firefox

- .github/workflows/build.yml
remove volta and use pnpm setup instead, which also sets up node
this also improves the CI to get closer to the publishing part, so setup for publish is tested as well
> fix publish - remove volta

- skeletons/web-extension/manifest.json
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/host_permissions
chrome already defaults to it when not specified
fixes #2516
> [firefox] set access permissions for all websites 

- app/services/adapters/web-extension.js
fixes #2532 
looks like service workers can be shutown after idle time... with manifest V3.
but it can be stopped any time, as it is not guaranteed.
also we reconnect immediately so that we can receive updates  when some start coming in from ember_debug site
https://developer.chrome.com/docs/extensions/develop/concepts/service-workers/lifecycle#idle-shutdown
tested manually by stopping the service worker in chrome://serviceworker-internals/?devtools
> ensure port is connected

- app/controllers/route-tree.js
- app/routes/route-tree.js
- app/templates/route-tree.hbs
- ember_debug/route-debug.js
* use backburner instead of setInterval
* use routeHandler.get
* show error if getting routes failed
> improve route debug

- package.json
- pnpm-lock.yaml
From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.
The dependency was added in https://github.com/emberjs/ember-inspector/pull/535 to upload panes.
It was not removed in https://github.com/emberjs/ember-inspector/pull/2103
> chore(deps): remove unused AWS SDK for JavaScript

- app/components/component-tree-arg.js
- app/components/component-tree-item.hbs
- app/components/object-inspector/property.ts
- app/controllers/component-tree.js
- app/styles/component_tree.scss
- ember-cli-build.js
- ember_debug/adapters/web-extension.js
- ember_debug/libs/render-tree.js
- ember_debug/object-inspector.js
- ember_debug/utils/get-object-name.js
- ember_debug/utils/type-check.js
- ember_debug/utils/version.js
- tests/ember_debug/view-debug-test.js
- tests/index.html
this adds modifiers and their html element to the render tree.
this also improves the UX for positional args, especially functions
this builds on #2549
> add modifiers to render tree

- app/components/object-inspector/dependent-keys.hbs
- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
this now also marks the changed dependent keys with a red text colour and adds a tooltip
> improve dependent keys ux

- .github/workflows/build.yml
- .github/workflows/plan-release.yml
- .github/workflows/publish.yml
- package.json
- pnpm-lock.yaml
i think it would be nice to have release-plan here as well
> add release plan

- .github/workflows/build.yml
- .github/workflows/publish.yml
this is needed so that the tag push triggers a workflow run, which will not happen if using gihub bot token
> Use GH_PAT token to hopefully fix releases

- ember_debug/libs/render-tree.js
for template only components coming from .hbs files we can know the name by using the moduleName.
this is when gjs/gts files import hbs template only components. Or also when references via js. e.g `<this.MyTemplateOnlyComponent />`
> provide name for hbs template only components

- app/components/object-inspector/property.ts
- tests/acceptance/object-inspector-test.js
> fix boolean edit

- app/components/object-inspector.js
- app/libs/resizable-columns.js
- tests/unit/resizable-columns-test.js
> Remove mapBy and filterBy

- app/components/object-inspector/sort-properties.js
- app/controllers/application.js
- app/libs/resizable-columns.js
- app/models/promise.js
- app/routes/application.js
- app/routes/deprecations.js
- app/routes/model-type.js
- app/routes/model-types.js
- app/routes/records.js
- ember_debug/object-inspector.js
- tests/ember_debug/container-debug-test.js
- tests/ember_debug/promise-debug-test.js
> cleanup filterBy & mapBy prototype extensions

- app/controllers/application.js
- app/controllers/deprecations.js
- app/controllers/promise-tree.js
- app/libs/promise-assembler.js
- app/models/promise.js
- app/routes/deprecations.js
- app/templates/deprecations.hbs
> More progress removing prototype extensions

- .github/workflows/build.yml
- config/ember-try.js
- package.json
- pnpm-lock.yaml
This PR adds explicit tests for Ember 5.8 and 5.12 and also temporarily turns off tests for canary, beta, and release as they are currently broken. I intend to open a PR to track support for 6.4 in a bit 👍
> test ember 5.8 and 5.12

- tests/helpers/trigger-port.js
There's no reference to the file `tests/helpers/trigger-port.js` in the current test suite. It seems that in the past, it was imported and used in files that no longer exist.
> Remove unused file `trigger-port.js`

- tests/ember_debug/view-debug-test.js
This PR prepares the ground for Ember 6 support.
In old Ember versions, components were not co-located with their template. Your component would live in `app/components/` and its template in `app/templates/components`. The class and the template were registered separately. The ember-inspector test `ember_debug/view-debug-test` was initially written with this approach in mind.
[Ember 3.13 introduced co-location](https://rfcs.emberjs.com/id/0481-component-templates-co-location/). The component and its template would live in `app/components/`, and the method `setComponentTemplate` was introduced to associate the template with the given class. The previous non-co-located structure was still valid, though, so the registration approach in the ember-inspector tests wasn't updated.
With Ember 6, …
> Prepare ember 6+ support/ view-debug

- .github/workflows/build.yml
- ember_debug/libs/render-tree.js
- ember_debug/utils/ember.js
- ember_debug/vendor/startup-wrapper.js
- tests/ember_debug/view-debug-test.js
- tests/integration/injection-test.js
This PR enables Ember 6.x support.
- It re-enables `ember-release`, `ember-beta`, and `ember-canary` scenarios on CI.
- It includes a few adjustments to Ember 6 (`runtime.NewTreeBuilder`, barrel file, routable components)
---
This PR was based on #2642, it takes only the commits that re-enable tests for Ember 6.
> Fix ember 6

- app/services/adapters/web-extension.ts
- tests/helpers/setup-ember-debug-test.js
- tests/integration/injection-test.js
- tests/test-helper.js
* the application route/controller/template of inspector ui was beeing indirectly used in ember_debug tests, which is not required and broke older lts tests
* the override of the adapter was happening to early and then it was again overridden in inspector ui init/setup
* port is not necessary for injection test and is breaking older lts tests, override with empty service
> fix ember 3.x-lts

- README.md
This PR is a proposal to make the documentation for development more verbose. The changes are the following:
- Indicate that if you use Ember Inspector already, you should first deactivate it. I didn't do it the first time I followed this doc, and it resulted in my local Ember Inspector not detecting the Ember app (I didn't investigate the mechanics behind that problem, but I assume that 2 inspectors trying to do things at the same time could trigger issues) 
- Be more specific about what runs where. What to do can be deduced easily enough by an experienced developer who already has a rough idea of how the inspector works, but I believe more precision could be helpful and precisely give some clues about how the inspector is supposed to load.
- Add the expected result, so a new contributor …
> docs: add precisions about running for development with bookmarklet

- ember_debug/utils/ember.js
- ember_debug/utils/ember/debug.js
- ember_debug/utils/ember/instrumentation.js
- ember_debug/utils/ember/object/internals.js
- ember_debug/utils/ember/runloop.js
- ember_debug/utils/rsvp.js
This PR is starting to split out the work from #2625 
This just tries to make sure that there is only one module that is calling requireModule and we can provide alternatives for the different environments isolated to that module 👍
> require all ember modules in one place

- app/routes/whats-new.js
- tests/acceptance/whats-new-test.js
whats new needs to fetch version with `-ember-inspector` suffix
> fix `whats new` not showing latest changes

- .github/workflows/build.yml
- ember_debug/package.json
- package.json
ember-debug was only build once when doing pnpm install. afterwards one had to notice to manually run build or watch for ember-debug.
this joins both into the root package.json for better local dev experience
> fix local dev

- ember_debug/object-inspector.js
- tests/ember_debug/object-inspector-test.js
The current code in object-inspector.js doesn't fit well how Services can be detected in the versions we support. Part of the code is now unused, and services appear in the inspector as Computed Properties.
this does the service detection by checking the value after obtaining the value
based on #2661 
before:
after
> fix service detection

- ember_debug/adapters/web-extension.js
- ember_debug/deprecation-debug.js
- ember_debug/general-debug.js
- ember_debug/libs/promise-assembler.js
- ember_debug/models/profile-manager.js
- ember_debug/promise-debug.js
- ember_debug/render-debug.js
- ember_debug/utils/ember.js
- ember_debug/utils/ember/debug.js
- ember_debug/utils/ember/instrumentation.js
- ember_debug/utils/ember/object/internals.js
- ember_debug/utils/ember/runloop.js
- ember_debug/utils/rsvp.js
- ember_debug/utils/type-check.js
This PR is part of preparing the ground for Vite support. When running the Inspector against a Vite app, the `Ember` global from `ember_debug/utils/ember` is undefined. The problem is twofold: first, the utils file itself is not prepared for this case; second, Ember is exported as default from the utils to be used in different places of the code. 
This PR:
- Complete the "centralization" work by removing all the `import Ember from 'ember_debug/utils/ember'` in favor of the named exports.
- Re-order things in the utils so we never try to access `Ember` properties if `Ember` is not defined.
> Cleanup import ember

- ember_debug/lib/get-applications.js
- ember_debug/lib/load-ember-debug-in-webpage.js
- ember_debug/lib/send-version-miss.js
- ember_debug/lib/setup-instance-initializer.js
- ember_debug/lib/start-inspector.js
- ember_debug/object-inspector.js
- ember_debug/utils/ember-object-names.js
- ember_debug/utils/ember.js
- package.json
- patches/ember-cli-inject-live-reload.patch
- pnpm-lock.yaml
- tests/ember_debug/container-debug-test.js
- tests/ember_debug/deprecation-debug-test.js
- tests/ember_debug/ember-data-test.js
- tests/ember_debug/ember-debug-test.js
- tests/ember_debug/object-inspector-test.js
- tests/ember_debug/profile-manager-test.js
- tests/ember_debug/profile-node-test.js
- tests/ember_debug/promise-assembler-test.js
- tests/ember_debug/promise-debug-test.js
- tests/ember_debug/render-debug-test.js
- tests/ember_debug/route-debug-test.js
- tests/ember_debug/view-debug-test.js
- tests/helpers/setup-ember-debug-test.js
- tests/integration/injection-test.js
- tests/unit/utils/type-check-test.js
This PR finalises a lot of work done to get the Ember Inspector to support Vite 🎉  This will require a global API that Embroider can polyfill after this PR is merged: https://github.com/embroider-build/embroider/pull/2522
There will be a follow up RFC that will move this polyfill implementation into ember-source 👍
> Add support for Vite
